/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50137
Source Host           : localhost:3306
Source Database       : rogue

Target Server Type    : MYSQL
Target Server Version : 50137
File Encoding         : 65001

Date: 2012-12-27 15:03:44
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `tbl_addressbook`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_addressbook`;
CREATE TABLE `tbl_addressbook` (
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `DataPlaceNumber` int(11) NOT NULL DEFAULT '0',
  `Level` int(11) DEFAULT NULL,
  `GraphicNo` int(11) DEFAULT NULL,
  `RegistSeqNumber` int(11) DEFAULT NULL,
  `ToRegistNumber` int(11) DEFAULT NULL,
  `ToCdKey` char(32) DEFAULT NULL,
  `OwnTitle` char(32) DEFAULT NULL,
  `CharName` char(32) DEFAULT NULL,
  `ToGuildID` int(11) DEFAULT NULL,
  `ToGuildTitle` int(11) DEFAULT NULL,
  PRIMARY KEY (`CdKey`,`RegistNumber`),
  KEY `index` (`CdKey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_addressbook
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_addressbook_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_addressbook_bak`;
CREATE TABLE `tbl_addressbook_bak` (
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `DataPlaceNumber` int(11) NOT NULL DEFAULT '0',
  `Level` int(11) DEFAULT NULL,
  `GraphicNo` int(11) DEFAULT NULL,
  `RegistSeqNumber` int(11) DEFAULT NULL,
  `ToRegistNumber` int(11) DEFAULT NULL,
  `ToCdKey` char(32) DEFAULT NULL,
  `OwnTitle` char(32) DEFAULT NULL,
  `CharName` char(32) DEFAULT NULL,
  `ToGuildID` int(11) DEFAULT NULL,
  `ToGuildTitle` int(11) DEFAULT NULL,
  PRIMARY KEY (`CdKey`,`RegistNumber`),
  KEY `index` (`CdKey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_addressbook_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_character`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_character`;
CREATE TABLE `tbl_character` (
  `WhichType` int(11) DEFAULT '0',
  `BaseImageNumber` int(11) DEFAULT '0',
  `BaseBaseImageNumber` int(11) DEFAULT '0',
  `MapID` int(11) DEFAULT '0',
  `Floor` int(11) DEFAULT '0',
  `X` int(11) DEFAULT '0',
  `Y` int(11) DEFAULT '0',
  `Dir` int(11) DEFAULT '0',
  `Lv` int(11) DEFAULT '0',
  `Hp` int(11) DEFAULT '0',
  `ForcePoint` int(11) DEFAULT '0',
  `Vital` int(11) DEFAULT '0',
  `Str` int(11) DEFAULT '0',
  `Tough` int(11) DEFAULT '0',
  `Quick` int(11) DEFAULT '0',
  `Magic` int(11) DEFAULT '0',
  `Luck` int(11) DEFAULT '0',
  `Tribe` int(11) DEFAULT '0',
  `Attrib_Fire` int(11) DEFAULT '0',
  `Attrib_Wind` int(11) DEFAULT '0',
  `Attrib_Earth` int(11) DEFAULT '0',
  `Attrib_Water` int(11) DEFAULT '0',
  `Poison` int(11) DEFAULT '0',
  `Sleep` int(11) DEFAULT '0',
  `Stone` int(11) DEFAULT '0',
  `Drunk` int(11) DEFAULT '0',
  `Confusion` int(11) DEFAULT '0',
  `Amnesia` int(11) DEFAULT '0',
  `Critical` int(11) DEFAULT '0',
  `Counter` int(11) DEFAULT '0',
  `HitRate` int(11) DEFAULT '0',
  `Avoid` int(11) DEFAULT '0',
  `ItemLimit` int(11) DEFAULT '0',
  `HaveSkillLimit` int(11) DEFAULT '0',
  `DeadCount` int(11) DEFAULT '0',
  `DamageCount` int(11) DEFAULT '0',
  `KillPetCount` int(11) DEFAULT '0',
  `LastTimeSetLuck` int(11) DEFAULT '0',
  `Injury` int(11) DEFAULT '0',
  `WalkInterval` int(11) DEFAULT '0',
  `LoopInterval` int(11) DEFAULT '0',
  `Exp` int(11) DEFAULT '0',
  `LevelUpPoint` int(11) DEFAULT '0',
  `ImageType` int(11) DEFAULT '0',
  `NameColor` int(11) DEFAULT '0',
  `AllocPoint` int(11) DEFAULT '0',
  `EatTime` int(11) DEFAULT '0',
  `DataPlaceNumber` int(11) DEFAULT '0',
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `MainJob` int(11) DEFAULT '0',
  `JobRank` int(11) DEFAULT '0',
  `JobAncestry` int(11) DEFAULT '0',
  `FaceImageNumber` int(11) DEFAULT '0',
  `Gold` int(11) DEFAULT '0',
  `PoolGold` int(11) DEFAULT '0',
  `Stamina` int(11) DEFAULT '0',
  `Dex` int(11) DEFAULT '0',
  `Intelligence` int(11) DEFAULT '0',
  `Charm` int(11) DEFAULT '0',
  `Fame` int(11) DEFAULT '0',
  `EquipTitle` int(11) DEFAULT '0',
  `SavePoint` int(11) DEFAULT '0',
  `DefaultPet` int(11) DEFAULT '0',
  `ChatVolume` int(11) DEFAULT '0',
  `HelpPoint` int(11) DEFAULT '0',
  `LoginCount` int(11) DEFAULT '0',
  `TalkCount` int(11) DEFAULT '0',
  `GetPetCount` int(11) DEFAULT '0',
  `SendMailCount` int(11) DEFAULT '0',
  `MergeItemCount` int(11) DEFAULT '0',
  `WalkCount` int(11) DEFAULT '0',
  `DeadPetCount` int(11) DEFAULT '0',
  `ResurrectPetCount` int(11) DEFAULT '0',
  `HealPetCount` int(11) DEFAULT '0',
  `CaptureCount` int(11) DEFAULT '0',
  `OtherFlg` int(11) DEFAULT '0',
  `FameGetValue` int(11) DEFAULT '0',
  `FameGetTime` int(11) DEFAULT '0',
  `FameAutoDownTime` int(11) DEFAULT '0',
  `SickLevel` int(11) DEFAULT '0',
  `RenewalFlg` int(11) DEFAULT '1',
  `EndEvent1` int(11) DEFAULT '0',
  `EndEvent2` int(11) DEFAULT '0',
  `EndEvent3` int(11) DEFAULT '0',
  `EndEvent4` int(11) DEFAULT '0',
  `EndEvent5` int(11) DEFAULT '0',
  `EndEvent6` int(11) DEFAULT '0',
  `EndEvent7` int(11) DEFAULT '0',
  `EndEvent8` int(11) DEFAULT '0',
  `NowEvent1` int(11) DEFAULT '0',
  `NowEvent2` int(11) DEFAULT '0',
  `NowEvent3` int(11) DEFAULT '0',
  `NowEvent4` int(11) DEFAULT '0',
  `NowEvent5` int(11) DEFAULT '0',
  `NowEvent6` int(11) DEFAULT '0',
  `NowEvent7` int(11) DEFAULT '0',
  `NowEvent8` int(11) DEFAULT '0',
  `Recipe1` int(11) DEFAULT '0',
  `Recipe2` int(11) DEFAULT '0',
  `Recipe3` int(11) DEFAULT '0',
  `Recipe4` int(11) DEFAULT '0',
  `Recipe5` int(11) DEFAULT '0',
  `Recipe6` int(11) DEFAULT '0',
  `Recipe7` int(11) DEFAULT '0',
  `Recipe8` int(11) DEFAULT '0',
  `Recipe9` int(11) DEFAULT '0',
  `Recipe10` int(11) DEFAULT '0',
  `Recipe11` int(11) DEFAULT '0',
  `Recipe12` int(11) DEFAULT '0',
  `Recipe13` int(11) DEFAULT '0',
  `Recipe14` int(11) DEFAULT '0',
  `Recipe15` int(11) DEFAULT '0',
  `Recipe16` int(11) DEFAULT '0',
  `Recipe17` int(11) DEFAULT '0',
  `Recipe18` int(11) DEFAULT '0',
  `Recipe19` int(11) DEFAULT '0',
  `Recipe20` int(11) DEFAULT '0',
  `Recipe21` int(11) DEFAULT '0',
  `Recipe22` int(11) DEFAULT '0',
  `Recipe23` int(11) DEFAULT '0',
  `Recipe24` int(11) DEFAULT '0',
  `Recipe25` int(11) DEFAULT '0',
  `Recipe26` int(11) DEFAULT '0',
  `Recipe27` int(11) DEFAULT '0',
  `Recipe28` int(11) DEFAULT '0',
  `Recipe29` int(11) DEFAULT '0',
  `Recipe30` int(11) DEFAULT '0',
  `Album1` int(11) DEFAULT '0',
  `Album2` int(11) DEFAULT '0',
  `Album3` int(11) DEFAULT '0',
  `Album4` int(11) DEFAULT '0',
  `Album5` int(11) DEFAULT '0',
  `Album6` int(11) DEFAULT '0',
  `Album7` int(11) DEFAULT '0',
  `Album8` int(11) DEFAULT '0',
  `Album9` int(11) DEFAULT '0',
  `Album10` int(11) DEFAULT '0',
  `MaxPoolPetHaveLimit` int(11) DEFAULT '0',
  `MaxPoolItemHaveLimit` int(11) DEFAULT '0',
  `DuelPoint` int(11) DEFAULT '0',
  `PopupNameColor` int(11) DEFAULT '0',
  `Position` int(11) DEFAULT '0',
  `Debugger` int(11) DEFAULT '0',
  `DungeonClr1` int(11) DEFAULT '0',
  `DungeonClr2` int(11) DEFAULT '0',
  `DungeonClr3` int(11) DEFAULT '0',
  `LastDaveTime` int(11) DEFAULT '0',
  `RankDownFlg` int(11) DEFAULT '0',
  `Renalty` int(11) DEFAULT '0',
  `LoginPoint` int(11) DEFAULT '0',
  `FeverResetTime` int(11) DEFAULT '0',
  `FeverHaveTime` int(11) DEFAULT '0',
  `HouseId` int(11) DEFAULT '0',
  `HouseLimit` int(11) DEFAULT '0',
  `TimeOutDungeonId` int(11) DEFAULT '0',
  `TimeOutServerNumber` int(11) DEFAULT '0',
  `OriginalImageNumber` int(11) DEFAULT '0',
  `Name` char(32) DEFAULT NULL,
  `OwnTitle` char(32) DEFAULT NULL,
  `CdKey` char(32) NOT NULL,
  `TitleID` int(11) DEFAULT '0',
  `PetSeqNo1` int(11) DEFAULT '0',
  `PetSeqNo2` int(11) DEFAULT '0',
  `PetSeqNo3` int(11) DEFAULT '0',
  `PetSeqNo4` int(11) DEFAULT '0',
  `PetSeqNo5` int(11) DEFAULT '0',
  `HaveTitleMakeId1` int(11) DEFAULT '0',
  `HaveTitleMakeId2` int(11) DEFAULT '0',
  `HaveTitleMakeId3` int(11) DEFAULT '0',
  `HaveTitleMakeId4` int(11) DEFAULT '0',
  `HaveTitleMakeId5` int(11) DEFAULT '0',
  `HaveTitleMakeId6` int(11) DEFAULT '0',
  `HaveTitleMakeId7` int(11) DEFAULT '0',
  `HaveTitleMakeId8` int(11) DEFAULT '0',
  `HaveTitleMakeId9` int(11) DEFAULT '0',
  `HaveTitleMakeId10` int(11) DEFAULT '0',
  `HaveTitleMakeId11` int(11) DEFAULT '0',
  `HaveTitleMakeId12` int(11) DEFAULT '0',
  `HaveTitleMakeId13` int(11) DEFAULT '0',
  `HaveTitleMakeId14` int(11) DEFAULT '0',
  `HaveTitleMakeId15` int(11) DEFAULT '0',
  `HaveTitleMakeId16` int(11) DEFAULT '0',
  `HaveTitleMakeId17` int(11) DEFAULT '0',
  `HaveTitleMakeId18` int(11) DEFAULT '0',
  `HaveTitleMakeId19` int(11) DEFAULT '0',
  `HaveTitleMakeId20` int(11) DEFAULT '0',
  `HaveTitleMakeId21` int(11) DEFAULT '0',
  `HaveTitleMakeId22` int(11) DEFAULT '0',
  `HaveTitleMakeId23` int(11) DEFAULT '0',
  `HaveTitleMakeId24` int(11) DEFAULT '0',
  `HaveTitleMakeId25` int(11) DEFAULT '0',
  `HaveTitleMakeId26` int(11) DEFAULT '0',
  `HaveTitleMakeId27` int(11) DEFAULT '0',
  `HaveTitleMakeId28` int(11) DEFAULT '0',
  `HaveTitleMakeId29` int(11) DEFAULT '0',
  `HaveTitleMakeId30` int(11) DEFAULT '0',
  `HaveTitleMakeId31` int(11) DEFAULT '0',
  `HaveTitleMakeId32` int(11) DEFAULT '0',
  `HaveTitleMakeId33` int(11) DEFAULT '0',
  `HaveTitleMakeId34` int(11) DEFAULT '0',
  `HaveTitleMakeId35` int(11) DEFAULT '0',
  `HaveTitleMakeId36` int(11) DEFAULT '0',
  `HaveTitleMakeId37` int(11) DEFAULT '0',
  `HaveTitleMakeId38` int(11) DEFAULT '0',
  `HaveTitleMakeId39` int(11) DEFAULT '0',
  `HaveTitleMakeId40` int(11) DEFAULT '0',
  `HaveTitleMakeId41` int(11) DEFAULT '0',
  `HaveTitleMakeId42` int(11) DEFAULT '0',
  `HaveTitleMakeId43` int(11) DEFAULT '0',
  `HaveTitleMakeId44` int(11) DEFAULT '0',
  `HaveTitleMakeId45` int(11) DEFAULT '0',
  `HaveTitleMakeId46` int(11) DEFAULT '0',
  `HaveTitleMakeId47` int(11) DEFAULT '0',
  `HaveTitleMakeId48` int(11) DEFAULT '0',
  `guildID` int(11) DEFAULT '-1',
  `GuildtitleID` int(11) DEFAULT '-1',
  `sequence` int(11) DEFAULT '-1',
  `closenessMonster1` int(11) DEFAULT '0',
  `closenessMonster2` int(11) DEFAULT '0',
  `closenessMonster3` int(11) DEFAULT '0',
  `sortType` int(11) DEFAULT '0',
  `globalFlag1` int(11) DEFAULT '0',
  `globalFlag2` int(11) DEFAULT '0',
  `globalFlag3` int(11) DEFAULT '0',
  `globalFlag4` int(11) DEFAULT '0',
  `globalFlag5` int(11) DEFAULT '0',
  `globalFlag6` int(11) DEFAULT '0',
  `globalFlag7` int(11) DEFAULT '0',
  `globalFlag8` int(11) DEFAULT '0',
  `globalFlag9` int(11) DEFAULT '0',
  `globalFlag10` int(11) DEFAULT '0',
  `globalFlag11` int(11) DEFAULT '0',
  `globalFlag12` int(11) DEFAULT '0',
  `globalFlag13` int(11) DEFAULT '0',
  `globalFlag14` int(11) DEFAULT '0',
  `globalFlag15` int(11) DEFAULT '0',
  `globalFlag16` int(11) DEFAULT '0',
  `indexOfHaveTitle1` int(11) DEFAULT '0',
  `indexOfHaveTitle2` int(11) DEFAULT '0',
  `indexOfHaveTitle3` int(11) DEFAULT '0',
  `indexOfHaveTitle4` int(11) DEFAULT '0',
  `indexOfHaveTitle5` int(11) DEFAULT '0',
  `7` int(11) DEFAULT '0',
  `8` int(11) DEFAULT '0',
  `9` int(11) DEFAULT '0',
  `10` int(11) DEFAULT '0',
  `11` int(11) DEFAULT '0',
  `12` int(11) DEFAULT '0',
  `13` int(11) DEFAULT '0',
  `14` int(11) DEFAULT '0',
  `15` int(11) DEFAULT '0',
  `16` int(11) DEFAULT '0',
  `17` int(11) DEFAULT '0',
  `18` int(11) DEFAULT '0',
  `19` int(11) DEFAULT '0',
  `20` int(11) DEFAULT '0',
  `21` int(11) DEFAULT '0',
  `22` int(11) DEFAULT '0',
  `23` int(11) DEFAULT '0',
  `24` int(11) DEFAULT '0',
  `25` int(11) DEFAULT '0',
  `26` int(11) DEFAULT '0',
  `27` int(11) DEFAULT '0',
  `28` int(11) DEFAULT '0',
  `29` int(11) DEFAULT '0',
  `30` int(11) DEFAULT '0',
  `31` int(11) DEFAULT '0',
  `32` int(11) DEFAULT '0',
  `33` int(11) DEFAULT '0',
  `34` int(11) DEFAULT '0',
  `35` int(11) DEFAULT '0',
  `36` int(11) DEFAULT '0',
  `37` int(11) DEFAULT '0',
  `38` int(11) DEFAULT '0',
  `39` int(11) DEFAULT '0',
  `40` int(11) DEFAULT '0',
  `41` int(11) DEFAULT '0',
  `42` int(11) DEFAULT '0',
  `43` int(11) DEFAULT '0',
  `44` int(11) DEFAULT '0',
  `45` int(11) DEFAULT '0',
  `46` int(11) DEFAULT '0',
  `47` int(11) DEFAULT '0',
  `48` int(11) DEFAULT '0',
  `49` int(11) DEFAULT '0',
  `50` int(11) DEFAULT '0',
  `51` int(11) DEFAULT '0',
  `52` int(11) DEFAULT '0',
  `53` int(11) DEFAULT '0',
  `54` int(11) DEFAULT '0',
  `55` int(11) DEFAULT '0',
  `56` int(11) DEFAULT '0',
  `57` int(11) DEFAULT '0',
  `58` int(11) DEFAULT '0',
  `59` int(11) DEFAULT '0',
  `60` int(11) DEFAULT '0',
  `61` int(11) DEFAULT '0',
  `62` int(11) DEFAULT '0',
  `63` int(11) DEFAULT '0',
  `64` int(11) DEFAULT '0',
  `65` int(11) DEFAULT '0',
  `66` int(11) DEFAULT '0',
  `67` int(11) DEFAULT '0',
  `68` int(11) DEFAULT '0',
  `69` int(11) DEFAULT '0',
  `70` int(11) DEFAULT '0',
  `71` int(11) DEFAULT '0',
  `72` int(11) DEFAULT '0',
  `73` int(11) DEFAULT '0',
  `74` int(11) DEFAULT '0',
  `75` int(11) DEFAULT '0',
  `76` int(11) DEFAULT '0',
  `77` int(11) DEFAULT '0',
  `78` int(11) DEFAULT '0',
  `79` int(11) DEFAULT '0',
  `80` int(11) DEFAULT '0',
  `81` int(11) DEFAULT '0',
  `82` int(11) DEFAULT '0',
  `83` int(11) DEFAULT '0',
  `globalFlag_T1` int(11) DEFAULT '0',
  `globalFlag_T2` int(11) DEFAULT '0',
  `globalFlag_T3` int(11) DEFAULT '0',
  `globalFlag_T4` int(11) DEFAULT '0',
  `globalFlag_T5` int(11) DEFAULT '0',
  `globalFlag_T6` int(11) DEFAULT '0',
  `globalFlag_T7` int(11) DEFAULT '0',
  `globalFlag_T8` int(11) DEFAULT '0',
  PRIMARY KEY (`RegistNumber`,`CdKey`),
  KEY `index` (`CdKey`,`RegistNumber`),
  KEY `index2` (`JobAncestry`,`Debugger`),
  KEY `index3` (`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_character
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_character_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_character_bak`;
CREATE TABLE `tbl_character_bak` (
  `WhichType` int(11) DEFAULT '0',
  `BaseImageNumber` int(11) DEFAULT '0',
  `BaseBaseImageNumber` int(11) DEFAULT '0',
  `MapID` int(11) DEFAULT '0',
  `Floor` int(11) DEFAULT '0',
  `X` int(11) DEFAULT '0',
  `Y` int(11) DEFAULT '0',
  `Dir` int(11) DEFAULT '0',
  `Lv` int(11) DEFAULT '0',
  `Hp` int(11) DEFAULT '0',
  `ForcePoint` int(11) DEFAULT '0',
  `Vital` int(11) DEFAULT '0',
  `Str` int(11) DEFAULT '0',
  `Tough` int(11) DEFAULT '0',
  `Quick` int(11) DEFAULT '0',
  `Magic` int(11) DEFAULT '0',
  `Luck` int(11) DEFAULT '0',
  `Tribe` int(11) DEFAULT '0',
  `Attrib_Fire` int(11) DEFAULT '0',
  `Attrib_Wind` int(11) DEFAULT '0',
  `Attrib_Earth` int(11) DEFAULT '0',
  `Attrib_Water` int(11) DEFAULT '0',
  `Poison` int(11) DEFAULT '0',
  `Sleep` int(11) DEFAULT '0',
  `Stone` int(11) DEFAULT '0',
  `Drunk` int(11) DEFAULT '0',
  `Confusion` int(11) DEFAULT '0',
  `Amnesia` int(11) DEFAULT '0',
  `Critical` int(11) DEFAULT '0',
  `Counter` int(11) DEFAULT '0',
  `HitRate` int(11) DEFAULT '0',
  `Avoid` int(11) DEFAULT '0',
  `ItemLimit` int(11) DEFAULT '0',
  `HaveSkillLimit` int(11) DEFAULT '0',
  `DeadCount` int(11) DEFAULT '0',
  `DamageCount` int(11) DEFAULT '0',
  `KillPetCount` int(11) DEFAULT '0',
  `LastTimeSetLuck` int(11) DEFAULT '0',
  `Injury` int(11) DEFAULT '0',
  `WalkInterval` int(11) DEFAULT '0',
  `LoopInterval` int(11) DEFAULT '0',
  `Exp` int(11) DEFAULT '0',
  `LevelUpPoint` int(11) DEFAULT '0',
  `ImageType` int(11) DEFAULT '0',
  `NameColor` int(11) DEFAULT '0',
  `AllocPoint` int(11) DEFAULT '0',
  `EatTime` int(11) DEFAULT '0',
  `DataPlaceNumber` int(11) DEFAULT '0',
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `MainJob` int(11) DEFAULT '0',
  `JobRank` int(11) DEFAULT '0',
  `JobAncestry` int(11) DEFAULT '0',
  `FaceImageNumber` int(11) DEFAULT '0',
  `Gold` int(11) DEFAULT '0',
  `PoolGold` int(11) DEFAULT '0',
  `Stamina` int(11) DEFAULT '0',
  `Dex` int(11) DEFAULT '0',
  `Intelligence` int(11) DEFAULT '0',
  `Charm` int(11) DEFAULT '0',
  `Fame` int(11) DEFAULT '0',
  `EquipTitle` int(11) DEFAULT '0',
  `SavePoint` int(11) DEFAULT '0',
  `DefaultPet` int(11) DEFAULT '0',
  `ChatVolume` int(11) DEFAULT '0',
  `HelpPoint` int(11) DEFAULT '0',
  `LoginCount` int(11) DEFAULT '0',
  `TalkCount` int(11) DEFAULT '0',
  `GetPetCount` int(11) DEFAULT '0',
  `SendMailCount` int(11) DEFAULT '0',
  `MergeItemCount` int(11) DEFAULT '0',
  `WalkCount` int(11) DEFAULT '0',
  `DeadPetCount` int(11) DEFAULT '0',
  `ResurrectPetCount` int(11) DEFAULT '0',
  `HealPetCount` int(11) DEFAULT '0',
  `CaptureCount` int(11) DEFAULT '0',
  `OtherFlg` int(11) DEFAULT '0',
  `FameGetValue` int(11) DEFAULT '0',
  `FameGetTime` int(11) DEFAULT '0',
  `FameAutoDownTime` int(11) DEFAULT '0',
  `SickLevel` int(11) DEFAULT '0',
  `RenewalFlg` int(11) DEFAULT '1',
  `EndEvent1` int(11) DEFAULT '0',
  `EndEvent2` int(11) DEFAULT '0',
  `EndEvent3` int(11) DEFAULT '0',
  `EndEvent4` int(11) DEFAULT '0',
  `EndEvent5` int(11) DEFAULT '0',
  `EndEvent6` int(11) DEFAULT '0',
  `EndEvent7` int(11) DEFAULT '0',
  `EndEvent8` int(11) DEFAULT '0',
  `NowEvent1` int(11) DEFAULT '0',
  `NowEvent2` int(11) DEFAULT '0',
  `NowEvent3` int(11) DEFAULT '0',
  `NowEvent4` int(11) DEFAULT '0',
  `NowEvent5` int(11) DEFAULT '0',
  `NowEvent6` int(11) DEFAULT '0',
  `NowEvent7` int(11) DEFAULT '0',
  `NowEvent8` int(11) DEFAULT '0',
  `Recipe1` int(11) DEFAULT '0',
  `Recipe2` int(11) DEFAULT '0',
  `Recipe3` int(11) DEFAULT '0',
  `Recipe4` int(11) DEFAULT '0',
  `Recipe5` int(11) DEFAULT '0',
  `Recipe6` int(11) DEFAULT '0',
  `Recipe7` int(11) DEFAULT '0',
  `Recipe8` int(11) DEFAULT '0',
  `Recipe9` int(11) DEFAULT '0',
  `Recipe10` int(11) DEFAULT '0',
  `Recipe11` int(11) DEFAULT '0',
  `Recipe12` int(11) DEFAULT '0',
  `Recipe13` int(11) DEFAULT '0',
  `Recipe14` int(11) DEFAULT '0',
  `Recipe15` int(11) DEFAULT '0',
  `Recipe16` int(11) DEFAULT '0',
  `Recipe17` int(11) DEFAULT '0',
  `Recipe18` int(11) DEFAULT '0',
  `Recipe19` int(11) DEFAULT '0',
  `Recipe20` int(11) DEFAULT '0',
  `Recipe21` int(11) DEFAULT '0',
  `Recipe22` int(11) DEFAULT '0',
  `Recipe23` int(11) DEFAULT '0',
  `Recipe24` int(11) DEFAULT '0',
  `Recipe25` int(11) DEFAULT '0',
  `Recipe26` int(11) DEFAULT '0',
  `Recipe27` int(11) DEFAULT '0',
  `Recipe28` int(11) DEFAULT '0',
  `Recipe29` int(11) DEFAULT '0',
  `Recipe30` int(11) DEFAULT '0',
  `Album1` int(11) DEFAULT '0',
  `Album2` int(11) DEFAULT '0',
  `Album3` int(11) DEFAULT '0',
  `Album4` int(11) DEFAULT '0',
  `Album5` int(11) DEFAULT '0',
  `Album6` int(11) DEFAULT '0',
  `Album7` int(11) DEFAULT '0',
  `Album8` int(11) DEFAULT '0',
  `Album9` int(11) DEFAULT '0',
  `Album10` int(11) DEFAULT '0',
  `MaxPoolPetHaveLimit` int(11) DEFAULT '0',
  `MaxPoolItemHaveLimit` int(11) DEFAULT '0',
  `DuelPoint` int(11) DEFAULT '0',
  `PopupNameColor` int(11) DEFAULT '0',
  `Position` int(11) DEFAULT '0',
  `Debugger` int(11) DEFAULT '0',
  `DungeonClr1` int(11) DEFAULT '0',
  `DungeonClr2` int(11) DEFAULT '0',
  `DungeonClr3` int(11) DEFAULT '0',
  `LastDaveTime` int(11) DEFAULT '0',
  `RankDownFlg` int(11) DEFAULT '0',
  `Renalty` int(11) DEFAULT '0',
  `LoginPoint` int(11) DEFAULT '0',
  `FeverResetTime` int(11) DEFAULT '0',
  `FeverHaveTime` int(11) DEFAULT '0',
  `HouseId` int(11) DEFAULT '0',
  `HouseLimit` int(11) DEFAULT '0',
  `TimeOutDungeonId` int(11) DEFAULT '0',
  `TimeOutServerNumber` int(11) DEFAULT '0',
  `OriginalImageNumber` int(11) DEFAULT '0',
  `Name` char(32) DEFAULT NULL,
  `OwnTitle` char(32) DEFAULT NULL,
  `CdKey` char(32) NOT NULL,
  `TitleID` int(11) DEFAULT '0',
  `PetSeqNo1` int(11) DEFAULT '0',
  `PetSeqNo2` int(11) DEFAULT '0',
  `PetSeqNo3` int(11) DEFAULT '0',
  `PetSeqNo4` int(11) DEFAULT '0',
  `PetSeqNo5` int(11) DEFAULT '0',
  `HaveTitleMakeId1` int(11) DEFAULT '0',
  `HaveTitleMakeId2` int(11) DEFAULT '0',
  `HaveTitleMakeId3` int(11) DEFAULT '0',
  `HaveTitleMakeId4` int(11) DEFAULT '0',
  `HaveTitleMakeId5` int(11) DEFAULT '0',
  `HaveTitleMakeId6` int(11) DEFAULT '0',
  `HaveTitleMakeId7` int(11) DEFAULT '0',
  `HaveTitleMakeId8` int(11) DEFAULT '0',
  `HaveTitleMakeId9` int(11) DEFAULT '0',
  `HaveTitleMakeId10` int(11) DEFAULT '0',
  `HaveTitleMakeId11` int(11) DEFAULT '0',
  `HaveTitleMakeId12` int(11) DEFAULT '0',
  `HaveTitleMakeId13` int(11) DEFAULT '0',
  `HaveTitleMakeId14` int(11) DEFAULT '0',
  `HaveTitleMakeId15` int(11) DEFAULT '0',
  `HaveTitleMakeId16` int(11) DEFAULT '0',
  `HaveTitleMakeId17` int(11) DEFAULT '0',
  `HaveTitleMakeId18` int(11) DEFAULT '0',
  `HaveTitleMakeId19` int(11) DEFAULT '0',
  `HaveTitleMakeId20` int(11) DEFAULT '0',
  `HaveTitleMakeId21` int(11) DEFAULT '0',
  `HaveTitleMakeId22` int(11) DEFAULT '0',
  `HaveTitleMakeId23` int(11) DEFAULT '0',
  `HaveTitleMakeId24` int(11) DEFAULT '0',
  `HaveTitleMakeId25` int(11) DEFAULT '0',
  `HaveTitleMakeId26` int(11) DEFAULT '0',
  `HaveTitleMakeId27` int(11) DEFAULT '0',
  `HaveTitleMakeId28` int(11) DEFAULT '0',
  `HaveTitleMakeId29` int(11) DEFAULT '0',
  `HaveTitleMakeId30` int(11) DEFAULT '0',
  `HaveTitleMakeId31` int(11) DEFAULT '0',
  `HaveTitleMakeId32` int(11) DEFAULT '0',
  `HaveTitleMakeId33` int(11) DEFAULT '0',
  `HaveTitleMakeId34` int(11) DEFAULT '0',
  `HaveTitleMakeId35` int(11) DEFAULT '0',
  `HaveTitleMakeId36` int(11) DEFAULT '0',
  `HaveTitleMakeId37` int(11) DEFAULT '0',
  `HaveTitleMakeId38` int(11) DEFAULT '0',
  `HaveTitleMakeId39` int(11) DEFAULT '0',
  `HaveTitleMakeId40` int(11) DEFAULT '0',
  `HaveTitleMakeId41` int(11) DEFAULT '0',
  `HaveTitleMakeId42` int(11) DEFAULT '0',
  `HaveTitleMakeId43` int(11) DEFAULT '0',
  `HaveTitleMakeId44` int(11) DEFAULT '0',
  `HaveTitleMakeId45` int(11) DEFAULT '0',
  `HaveTitleMakeId46` int(11) DEFAULT '0',
  `HaveTitleMakeId47` int(11) DEFAULT '0',
  `HaveTitleMakeId48` int(11) DEFAULT '0',
  `guildID` int(11) DEFAULT '-1',
  `GuildtitleID` int(11) DEFAULT '-1',
  `sequence` int(11) DEFAULT '-1',
  `closenessMonster1` int(11) DEFAULT '0',
  `closenessMonster2` int(11) DEFAULT '0',
  `closenessMonster3` int(11) DEFAULT '0',
  `sortType` int(11) DEFAULT '0',
  `globalFlag1` int(11) DEFAULT '0',
  `globalFlag2` int(11) DEFAULT '0',
  `globalFlag3` int(11) DEFAULT '0',
  `globalFlag4` int(11) DEFAULT '0',
  `globalFlag5` int(11) DEFAULT '0',
  `globalFlag6` int(11) DEFAULT '0',
  `globalFlag7` int(11) DEFAULT '0',
  `globalFlag8` int(11) DEFAULT '0',
  `globalFlag9` int(11) DEFAULT '0',
  `globalFlag10` int(11) DEFAULT '0',
  `globalFlag11` int(11) DEFAULT '0',
  `globalFlag12` int(11) DEFAULT '0',
  `globalFlag13` int(11) DEFAULT '0',
  `globalFlag14` int(11) DEFAULT '0',
  `globalFlag15` int(11) DEFAULT '0',
  `globalFlag16` int(11) DEFAULT '0',
  `indexOfHaveTitle1` int(11) DEFAULT '0',
  `indexOfHaveTitle2` int(11) DEFAULT '0',
  `indexOfHaveTitle3` int(11) DEFAULT '0',
  `indexOfHaveTitle4` int(11) DEFAULT '0',
  `indexOfHaveTitle5` int(11) DEFAULT '0',
  `7` int(11) DEFAULT '0',
  `8` int(11) DEFAULT '0',
  `9` int(11) DEFAULT '0',
  `10` int(11) DEFAULT '0',
  `11` int(11) DEFAULT '0',
  `12` int(11) DEFAULT '0',
  `13` int(11) DEFAULT '0',
  `14` int(11) DEFAULT '0',
  `15` int(11) DEFAULT '0',
  `16` int(11) DEFAULT '0',
  `17` int(11) DEFAULT '0',
  `18` int(11) DEFAULT '0',
  `19` int(11) DEFAULT '0',
  `20` int(11) DEFAULT '0',
  `21` int(11) DEFAULT '0',
  `22` int(11) DEFAULT '0',
  `23` int(11) DEFAULT '0',
  `24` int(11) DEFAULT '0',
  `25` int(11) DEFAULT '0',
  `26` int(11) DEFAULT '0',
  `27` int(11) DEFAULT '0',
  `28` int(11) DEFAULT '0',
  `29` int(11) DEFAULT '0',
  `30` int(11) DEFAULT '0',
  `31` int(11) DEFAULT '0',
  `32` int(11) DEFAULT '0',
  `33` int(11) DEFAULT '0',
  `34` int(11) DEFAULT '0',
  `35` int(11) DEFAULT '0',
  `36` int(11) DEFAULT '0',
  `37` int(11) DEFAULT '0',
  `38` int(11) DEFAULT '0',
  `39` int(11) DEFAULT '0',
  `40` int(11) DEFAULT '0',
  `41` int(11) DEFAULT '0',
  `42` int(11) DEFAULT '0',
  `43` int(11) DEFAULT '0',
  `44` int(11) DEFAULT '0',
  `45` int(11) DEFAULT '0',
  `46` int(11) DEFAULT '0',
  `47` int(11) DEFAULT '0',
  `48` int(11) DEFAULT '0',
  `49` int(11) DEFAULT '0',
  `50` int(11) DEFAULT '0',
  `51` int(11) DEFAULT '0',
  `52` int(11) DEFAULT '0',
  `53` int(11) DEFAULT '0',
  `54` int(11) DEFAULT '0',
  `55` int(11) DEFAULT '0',
  `56` int(11) DEFAULT '0',
  `57` int(11) DEFAULT '0',
  `58` int(11) DEFAULT '0',
  `59` int(11) DEFAULT '0',
  `60` int(11) DEFAULT '0',
  `61` int(11) DEFAULT '0',
  `62` int(11) DEFAULT '0',
  `63` int(11) DEFAULT '0',
  `64` int(11) DEFAULT '0',
  `65` int(11) DEFAULT '0',
  `66` int(11) DEFAULT '0',
  `67` int(11) DEFAULT '0',
  `68` int(11) DEFAULT '0',
  `69` int(11) DEFAULT '0',
  `70` int(11) DEFAULT '0',
  `71` int(11) DEFAULT '0',
  `72` int(11) DEFAULT '0',
  `73` int(11) DEFAULT '0',
  `74` int(11) DEFAULT '0',
  `75` int(11) DEFAULT '0',
  `76` int(11) DEFAULT '0',
  `77` int(11) DEFAULT '0',
  `78` int(11) DEFAULT '0',
  `79` int(11) DEFAULT '0',
  `80` int(11) DEFAULT '0',
  `81` int(11) DEFAULT '0',
  `82` int(11) DEFAULT '0',
  `83` int(11) DEFAULT '0',
  `globalFlag_T1` int(11) DEFAULT '0',
  `globalFlag_T2` int(11) DEFAULT '0',
  `globalFlag_T3` int(11) DEFAULT '0',
  `globalFlag_T4` int(11) DEFAULT '0',
  `globalFlag_T5` int(11) DEFAULT '0',
  `globalFlag_T6` int(11) DEFAULT '0',
  `globalFlag_T7` int(11) DEFAULT '0',
  `globalFlag_T8` int(11) DEFAULT '0',
  PRIMARY KEY (`RegistNumber`,`CdKey`),
  KEY `index` (`CdKey`,`RegistNumber`),
  KEY `index2` (`JobAncestry`,`Debugger`),
  KEY `index3` (`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_character_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_character_down`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_character_down`;
CREATE TABLE `tbl_character_down` (
  `WhichType` int(11) DEFAULT '0',
  `BaseImageNumber` int(11) DEFAULT '0',
  `BaseBaseImageNumber` int(11) DEFAULT '0',
  `MapID` int(11) DEFAULT '0',
  `Floor` int(11) DEFAULT '0',
  `X` int(11) DEFAULT '0',
  `Y` int(11) DEFAULT '0',
  `Dir` int(11) DEFAULT '0',
  `Lv` int(11) DEFAULT '0',
  `Hp` int(11) DEFAULT '0',
  `ForcePoint` int(11) DEFAULT '0',
  `Vital` int(11) DEFAULT '0',
  `Str` int(11) DEFAULT '0',
  `Tough` int(11) DEFAULT '0',
  `Quick` int(11) DEFAULT '0',
  `Magic` int(11) DEFAULT '0',
  `Luck` int(11) DEFAULT '0',
  `Tribe` int(11) DEFAULT '0',
  `Attrib_Fire` int(11) DEFAULT '0',
  `Attrib_Wind` int(11) DEFAULT '0',
  `Attrib_Earth` int(11) DEFAULT '0',
  `Attrib_Water` int(11) DEFAULT '0',
  `Poison` int(11) DEFAULT '0',
  `Sleep` int(11) DEFAULT '0',
  `Stone` int(11) DEFAULT '0',
  `Drunk` int(11) DEFAULT '0',
  `Confusion` int(11) DEFAULT '0',
  `Amnesia` int(11) DEFAULT '0',
  `Critical` int(11) DEFAULT '0',
  `Counter` int(11) DEFAULT '0',
  `HitRate` int(11) DEFAULT '0',
  `Avoid` int(11) DEFAULT '0',
  `ItemLimit` int(11) DEFAULT '0',
  `HaveSkillLimit` int(11) DEFAULT '0',
  `DeadCount` int(11) DEFAULT '0',
  `DamageCount` int(11) DEFAULT '0',
  `KillPetCount` int(11) DEFAULT '0',
  `LastTimeSetLuck` int(11) DEFAULT '0',
  `Injury` int(11) DEFAULT '0',
  `WalkInterval` int(11) DEFAULT '0',
  `LoopInterval` int(11) DEFAULT '0',
  `Exp` int(11) DEFAULT '0',
  `LevelUpPoint` int(11) DEFAULT '0',
  `ImageType` int(11) DEFAULT '0',
  `NameColor` int(11) DEFAULT '0',
  `AllocPoint` int(11) DEFAULT '0',
  `EatTime` int(11) DEFAULT '0',
  `DataPlaceNumber` int(11) DEFAULT '0',
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `MainJob` int(11) DEFAULT '0',
  `JobRank` int(11) DEFAULT '0',
  `JobAncestry` int(11) DEFAULT '0',
  `FaceImageNumber` int(11) DEFAULT '0',
  `Gold` int(11) DEFAULT '0',
  `PoolGold` int(11) DEFAULT '0',
  `Stamina` int(11) DEFAULT '0',
  `Dex` int(11) DEFAULT '0',
  `Intelligence` int(11) DEFAULT '0',
  `Charm` int(11) DEFAULT '0',
  `Fame` int(11) DEFAULT '0',
  `EquipTitle` int(11) DEFAULT '0',
  `SavePoint` int(11) DEFAULT '0',
  `DefaultPet` int(11) DEFAULT '0',
  `ChatVolume` int(11) DEFAULT '0',
  `HelpPoint` int(11) DEFAULT '0',
  `LoginCount` int(11) DEFAULT '0',
  `TalkCount` int(11) DEFAULT '0',
  `GetPetCount` int(11) DEFAULT '0',
  `SendMailCount` int(11) DEFAULT '0',
  `MergeItemCount` int(11) DEFAULT '0',
  `WalkCount` int(11) DEFAULT '0',
  `DeadPetCount` int(11) DEFAULT '0',
  `ResurrectPetCount` int(11) DEFAULT '0',
  `HealPetCount` int(11) DEFAULT '0',
  `CaptureCount` int(11) DEFAULT '0',
  `OtherFlg` int(11) DEFAULT '0',
  `FameGetValue` int(11) DEFAULT '0',
  `FameGetTime` int(11) DEFAULT '0',
  `FameAutoDownTime` int(11) DEFAULT '0',
  `SickLevel` int(11) DEFAULT '0',
  `RenewalFlg` int(11) DEFAULT '1',
  `EndEvent1` int(11) DEFAULT '0',
  `EndEvent2` int(11) DEFAULT '0',
  `EndEvent3` int(11) DEFAULT '0',
  `EndEvent4` int(11) DEFAULT '0',
  `EndEvent5` int(11) DEFAULT '0',
  `EndEvent6` int(11) DEFAULT '0',
  `EndEvent7` int(11) DEFAULT '0',
  `EndEvent8` int(11) DEFAULT '0',
  `NowEvent1` int(11) DEFAULT '0',
  `NowEvent2` int(11) DEFAULT '0',
  `NowEvent3` int(11) DEFAULT '0',
  `NowEvent4` int(11) DEFAULT '0',
  `NowEvent5` int(11) DEFAULT '0',
  `NowEvent6` int(11) DEFAULT '0',
  `NowEvent7` int(11) DEFAULT '0',
  `NowEvent8` int(11) DEFAULT '0',
  `Recipe1` int(11) DEFAULT '0',
  `Recipe2` int(11) DEFAULT '0',
  `Recipe3` int(11) DEFAULT '0',
  `Recipe4` int(11) DEFAULT '0',
  `Recipe5` int(11) DEFAULT '0',
  `Recipe6` int(11) DEFAULT '0',
  `Recipe7` int(11) DEFAULT '0',
  `Recipe8` int(11) DEFAULT '0',
  `Recipe9` int(11) DEFAULT '0',
  `Recipe10` int(11) DEFAULT '0',
  `Recipe11` int(11) DEFAULT '0',
  `Recipe12` int(11) DEFAULT '0',
  `Recipe13` int(11) DEFAULT '0',
  `Recipe14` int(11) DEFAULT '0',
  `Recipe15` int(11) DEFAULT '0',
  `Recipe16` int(11) DEFAULT '0',
  `Recipe17` int(11) DEFAULT '0',
  `Recipe18` int(11) DEFAULT '0',
  `Recipe19` int(11) DEFAULT '0',
  `Recipe20` int(11) DEFAULT '0',
  `Recipe21` int(11) DEFAULT '0',
  `Recipe22` int(11) DEFAULT '0',
  `Recipe23` int(11) DEFAULT '0',
  `Recipe24` int(11) DEFAULT '0',
  `Recipe25` int(11) DEFAULT '0',
  `Recipe26` int(11) DEFAULT '0',
  `Recipe27` int(11) DEFAULT '0',
  `Recipe28` int(11) DEFAULT '0',
  `Recipe29` int(11) DEFAULT '0',
  `Recipe30` int(11) DEFAULT '0',
  `Album1` int(11) DEFAULT '0',
  `Album2` int(11) DEFAULT '0',
  `Album3` int(11) DEFAULT '0',
  `Album4` int(11) DEFAULT '0',
  `Album5` int(11) DEFAULT '0',
  `Album6` int(11) DEFAULT '0',
  `Album7` int(11) DEFAULT '0',
  `Album8` int(11) DEFAULT '0',
  `Album9` int(11) DEFAULT '0',
  `Album10` int(11) DEFAULT '0',
  `MaxPoolPetHaveLimit` int(11) DEFAULT '0',
  `MaxPoolItemHaveLimit` int(11) DEFAULT '0',
  `DuelPoint` int(11) DEFAULT '0',
  `PopupNameColor` int(11) DEFAULT '0',
  `Position` int(11) DEFAULT '0',
  `Debugger` int(11) DEFAULT '0',
  `DungeonClr1` int(11) DEFAULT '0',
  `DungeonClr2` int(11) DEFAULT '0',
  `DungeonClr3` int(11) DEFAULT '0',
  `LastDaveTime` int(11) DEFAULT '0',
  `RankDownFlg` int(11) DEFAULT '0',
  `Renalty` int(11) DEFAULT '0',
  `LoginPoint` int(11) DEFAULT '0',
  `FeverResetTime` int(11) DEFAULT '0',
  `FeverHaveTime` int(11) DEFAULT '0',
  `HouseId` int(11) DEFAULT '0',
  `HouseLimit` int(11) DEFAULT '0',
  `TimeOutDungeonId` int(11) DEFAULT '0',
  `TimeOutServerNumber` int(11) DEFAULT '0',
  `OriginalImageNumber` int(11) DEFAULT '0',
  `Name` char(32) DEFAULT NULL,
  `OwnTitle` char(32) DEFAULT NULL,
  `CdKey` char(32) NOT NULL,
  `TitleID` int(11) DEFAULT '0',
  `PetSeqNo1` int(11) DEFAULT '0',
  `PetSeqNo2` int(11) DEFAULT '0',
  `PetSeqNo3` int(11) DEFAULT '0',
  `PetSeqNo4` int(11) DEFAULT '0',
  `PetSeqNo5` int(11) DEFAULT '0',
  `HaveTitleMakeId1` int(11) DEFAULT '0',
  `HaveTitleMakeId2` int(11) DEFAULT '0',
  `HaveTitleMakeId3` int(11) DEFAULT '0',
  `HaveTitleMakeId4` int(11) DEFAULT '0',
  `HaveTitleMakeId5` int(11) DEFAULT '0',
  `HaveTitleMakeId6` int(11) DEFAULT '0',
  `HaveTitleMakeId7` int(11) DEFAULT '0',
  `HaveTitleMakeId8` int(11) DEFAULT '0',
  `HaveTitleMakeId9` int(11) DEFAULT '0',
  `HaveTitleMakeId10` int(11) DEFAULT '0',
  `HaveTitleMakeId11` int(11) DEFAULT '0',
  `HaveTitleMakeId12` int(11) DEFAULT '0',
  `HaveTitleMakeId13` int(11) DEFAULT '0',
  `HaveTitleMakeId14` int(11) DEFAULT '0',
  `HaveTitleMakeId15` int(11) DEFAULT '0',
  `HaveTitleMakeId16` int(11) DEFAULT '0',
  `HaveTitleMakeId17` int(11) DEFAULT '0',
  `HaveTitleMakeId18` int(11) DEFAULT '0',
  `HaveTitleMakeId19` int(11) DEFAULT '0',
  `HaveTitleMakeId20` int(11) DEFAULT '0',
  `HaveTitleMakeId21` int(11) DEFAULT '0',
  `HaveTitleMakeId22` int(11) DEFAULT '0',
  `HaveTitleMakeId23` int(11) DEFAULT '0',
  `HaveTitleMakeId24` int(11) DEFAULT '0',
  `HaveTitleMakeId25` int(11) DEFAULT '0',
  `HaveTitleMakeId26` int(11) DEFAULT '0',
  `HaveTitleMakeId27` int(11) DEFAULT '0',
  `HaveTitleMakeId28` int(11) DEFAULT '0',
  `HaveTitleMakeId29` int(11) DEFAULT '0',
  `HaveTitleMakeId30` int(11) DEFAULT '0',
  `HaveTitleMakeId31` int(11) DEFAULT '0',
  `HaveTitleMakeId32` int(11) DEFAULT '0',
  `HaveTitleMakeId33` int(11) DEFAULT '0',
  `HaveTitleMakeId34` int(11) DEFAULT '0',
  `HaveTitleMakeId35` int(11) DEFAULT '0',
  `HaveTitleMakeId36` int(11) DEFAULT '0',
  `HaveTitleMakeId37` int(11) DEFAULT '0',
  `HaveTitleMakeId38` int(11) DEFAULT '0',
  `HaveTitleMakeId39` int(11) DEFAULT '0',
  `HaveTitleMakeId40` int(11) DEFAULT '0',
  `HaveTitleMakeId41` int(11) DEFAULT '0',
  `HaveTitleMakeId42` int(11) DEFAULT '0',
  `HaveTitleMakeId43` int(11) DEFAULT '0',
  `HaveTitleMakeId44` int(11) DEFAULT '0',
  `HaveTitleMakeId45` int(11) DEFAULT '0',
  `HaveTitleMakeId46` int(11) DEFAULT '0',
  `HaveTitleMakeId47` int(11) DEFAULT '0',
  `HaveTitleMakeId48` int(11) DEFAULT '0',
  `guildID` int(11) DEFAULT '-1',
  `GuildtitleID` int(11) DEFAULT '-1',
  `sequence` int(11) DEFAULT '-1',
  `closenessMonster1` int(11) DEFAULT '0',
  `closenessMonster2` int(11) DEFAULT '0',
  `closenessMonster3` int(11) DEFAULT '0',
  `sortType` int(11) DEFAULT '0',
  `globalFlag1` int(11) DEFAULT '0',
  `globalFlag2` int(11) DEFAULT '0',
  `globalFlag3` int(11) DEFAULT '0',
  `globalFlag4` int(11) DEFAULT '0',
  `globalFlag5` int(11) DEFAULT '0',
  `globalFlag6` int(11) DEFAULT '0',
  `globalFlag7` int(11) DEFAULT '0',
  `globalFlag8` int(11) DEFAULT '0',
  `globalFlag9` int(11) DEFAULT '0',
  `globalFlag10` int(11) DEFAULT '0',
  `globalFlag11` int(11) DEFAULT '0',
  `globalFlag12` int(11) DEFAULT '0',
  `globalFlag13` int(11) DEFAULT '0',
  `globalFlag14` int(11) DEFAULT '0',
  `globalFlag15` int(11) DEFAULT '0',
  `globalFlag16` int(11) DEFAULT '0',
  `indexOfHaveTitle1` int(11) DEFAULT '0',
  `indexOfHaveTitle2` int(11) DEFAULT '0',
  `indexOfHaveTitle3` int(11) DEFAULT '0',
  `indexOfHaveTitle4` int(11) DEFAULT '0',
  `indexOfHaveTitle5` int(11) DEFAULT '0',
  `7` int(11) DEFAULT '0',
  `8` int(11) DEFAULT '0',
  `9` int(11) DEFAULT '0',
  `10` int(11) DEFAULT '0',
  `11` int(11) DEFAULT '0',
  `12` int(11) DEFAULT '0',
  `13` int(11) DEFAULT '0',
  `14` int(11) DEFAULT '0',
  `15` int(11) DEFAULT '0',
  `16` int(11) DEFAULT '0',
  `17` int(11) DEFAULT '0',
  `18` int(11) DEFAULT '0',
  `19` int(11) DEFAULT '0',
  `20` int(11) DEFAULT '0',
  `21` int(11) DEFAULT '0',
  `22` int(11) DEFAULT '0',
  `23` int(11) DEFAULT '0',
  `24` int(11) DEFAULT '0',
  `25` int(11) DEFAULT '0',
  `26` int(11) DEFAULT '0',
  `27` int(11) DEFAULT '0',
  `28` int(11) DEFAULT '0',
  `29` int(11) DEFAULT '0',
  `30` int(11) DEFAULT '0',
  `31` int(11) DEFAULT '0',
  `32` int(11) DEFAULT '0',
  `33` int(11) DEFAULT '0',
  `34` int(11) DEFAULT '0',
  `35` int(11) DEFAULT '0',
  `36` int(11) DEFAULT '0',
  `37` int(11) DEFAULT '0',
  `38` int(11) DEFAULT '0',
  `39` int(11) DEFAULT '0',
  `40` int(11) DEFAULT '0',
  `41` int(11) DEFAULT '0',
  `42` int(11) DEFAULT '0',
  `43` int(11) DEFAULT '0',
  `44` int(11) DEFAULT '0',
  `45` int(11) DEFAULT '0',
  `46` int(11) DEFAULT '0',
  `47` int(11) DEFAULT '0',
  `48` int(11) DEFAULT '0',
  `49` int(11) DEFAULT '0',
  `50` int(11) DEFAULT '0',
  `51` int(11) DEFAULT '0',
  `52` int(11) DEFAULT '0',
  `53` int(11) DEFAULT '0',
  `54` int(11) DEFAULT '0',
  `55` int(11) DEFAULT '0',
  `56` int(11) DEFAULT '0',
  `57` int(11) DEFAULT '0',
  `58` int(11) DEFAULT '0',
  `59` int(11) DEFAULT '0',
  `60` int(11) DEFAULT '0',
  `61` int(11) DEFAULT '0',
  `62` int(11) DEFAULT '0',
  `63` int(11) DEFAULT '0',
  `64` int(11) DEFAULT '0',
  `65` int(11) DEFAULT '0',
  `66` int(11) DEFAULT '0',
  `67` int(11) DEFAULT '0',
  `68` int(11) DEFAULT '0',
  `69` int(11) DEFAULT '0',
  `70` int(11) DEFAULT '0',
  `71` int(11) DEFAULT '0',
  `72` int(11) DEFAULT '0',
  `73` int(11) DEFAULT '0',
  `74` int(11) DEFAULT '0',
  `75` int(11) DEFAULT '0',
  `76` int(11) DEFAULT '0',
  `77` int(11) DEFAULT '0',
  `78` int(11) DEFAULT '0',
  `79` int(11) DEFAULT '0',
  `80` int(11) DEFAULT '0',
  `81` int(11) DEFAULT '0',
  `82` int(11) DEFAULT '0',
  `83` int(11) DEFAULT '0',
  `globalFlag_T1` int(11) DEFAULT '0',
  `globalFlag_T2` int(11) DEFAULT '0',
  `globalFlag_T3` int(11) DEFAULT '0',
  `globalFlag_T4` int(11) DEFAULT '0',
  `globalFlag_T5` int(11) DEFAULT '0',
  `globalFlag_T6` int(11) DEFAULT '0',
  `globalFlag_T7` int(11) DEFAULT '0',
  `globalFlag_T8` int(11) DEFAULT '0',
  PRIMARY KEY (`RegistNumber`,`CdKey`),
  KEY `index` (`CdKey`,`RegistNumber`),
  KEY `index2` (`JobAncestry`,`Debugger`),
  KEY `index3` (`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_character_down
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_duelranking`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_duelranking`;
CREATE TABLE `tbl_duelranking` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `AccountID` int(11) DEFAULT NULL,
  `Name` char(32) DEFAULT NULL,
  `Lv` int(11) DEFAULT NULL,
  `DuelPoint` int(11) DEFAULT NULL,
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(11) DEFAULT NULL,
  PRIMARY KEY (`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_duelranking
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_graduation`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_graduation`;
CREATE TABLE `tbl_graduation` (
  `ProductKey` char(30) DEFAULT NULL,
  `Kind` char(30) DEFAULT NULL,
  `UseFlg` char(30) DEFAULT NULL,
  `LinkCdKey` char(30) DEFAULT NULL,
  `EnableFlg` char(30) DEFAULT NULL,
  `Key` char(30) DEFAULT NULL,
  `mode` char(30) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_graduation
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guild`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guild`;
CREATE TABLE `tbl_guild` (
  `guildID` int(10) NOT NULL AUTO_INCREMENT,
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(10) NOT NULL DEFAULT '-1',
  `serverNumber` tinyint(4) DEFAULT '-1',
  `roomType` int(10) DEFAULT '-1',
  `guildName` char(32) DEFAULT '',
  `roomName` char(32) DEFAULT '',
  `brief` char(100) DEFAULT '',
  `createTime` int(10) DEFAULT '0',
  `lastAccess` int(10) DEFAULT '0',
  `guildMark` int(10) DEFAULT '-1',
  `titleName0` char(32) DEFAULT '',
  `commition0` tinyint(4) DEFAULT '0',
  `titleName1` char(32) DEFAULT '',
  `commition1` tinyint(4) DEFAULT '0',
  `titleName2` char(32) DEFAULT '',
  `commition2` tinyint(4) DEFAULT '0',
  `titleName3` char(32) DEFAULT '',
  `commition3` tinyint(4) DEFAULT '0',
  `titleName4` char(32) DEFAULT '',
  `commition4` tinyint(4) DEFAULT '0',
  `titleName5` char(32) DEFAULT '',
  `commition5` tinyint(4) DEFAULT '0',
  `titleName6` char(32) DEFAULT '',
  `commition6` tinyint(4) DEFAULT '0',
  `titleName7` char(32) DEFAULT '',
  `commition7` tinyint(4) DEFAULT '0',
  `titleName8` char(32) DEFAULT '',
  `commition8` tinyint(4) DEFAULT '0',
  `titleName9` char(32) DEFAULT '',
  `commition9` tinyint(4) DEFAULT '0',
  `titleName10` char(32) DEFAULT '',
  `commition10` tinyint(4) DEFAULT '0',
  `titleName11` char(32) DEFAULT '',
  `commition11` tinyint(4) DEFAULT '0',
  `titleName12` char(32) DEFAULT '',
  `commition12` tinyint(4) DEFAULT '0',
  `titleName13` char(32) DEFAULT '',
  `commition13` tinyint(4) DEFAULT '0',
  `titleName14` char(32) DEFAULT '',
  `commition14` tinyint(4) DEFAULT '0',
  `titleName15` char(32) DEFAULT '',
  `commition15` tinyint(4) DEFAULT '0',
  `titleName16` char(32) DEFAULT '',
  `commition16` tinyint(4) DEFAULT '0',
  `titleName17` char(32) DEFAULT '',
  `commition17` tinyint(4) DEFAULT '0',
  `titleName18` char(32) DEFAULT '',
  `commition18` tinyint(4) DEFAULT '0',
  `titleName19` char(32) DEFAULT '',
  `commition19` tinyint(4) DEFAULT '0',
  `titleName20` char(32) DEFAULT '',
  `commition20` tinyint(4) DEFAULT '0',
  `titleName21` char(32) DEFAULT '',
  `commition21` tinyint(4) DEFAULT '0',
  `titleName22` char(32) DEFAULT '',
  `commition22` tinyint(4) DEFAULT '0',
  `titleName23` char(32) DEFAULT '',
  `commition23` tinyint(4) DEFAULT '0',
  `titleName24` char(32) DEFAULT '',
  `commition24` tinyint(4) DEFAULT '0',
  `titleName25` char(32) DEFAULT '',
  `commition25` tinyint(4) DEFAULT '0',
  `titleName26` char(32) DEFAULT '',
  `commition26` tinyint(4) DEFAULT '0',
  `titleName27` char(32) DEFAULT '',
  `commition27` tinyint(4) DEFAULT '0',
  `titleName28` char(32) DEFAULT '',
  `commition28` tinyint(4) DEFAULT '0',
  `titleName29` char(32) DEFAULT '',
  `commition29` tinyint(4) DEFAULT '0',
  `titleName30` char(32) DEFAULT '',
  `commition30` tinyint(4) DEFAULT '0',
  `titleName31` char(32) DEFAULT '',
  `commition31` tinyint(4) DEFAULT '0',
  `floorID` int(11) DEFAULT NULL,
  PRIMARY KEY (`guildID`,`CdKey`,`RegistNumber`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guild
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guilditembox`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guilditembox`;
CREATE TABLE `tbl_guilditembox` (
  `ID` int(30) NOT NULL DEFAULT '0',
  `AccountID` char(30) DEFAULT NULL,
  `GuildID` char(30) DEFAULT NULL,
  `CdKey` char(30) DEFAULT NULL,
  `RegistNumber` char(30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guilditembox
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guilditemboxpet`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guilditemboxpet`;
CREATE TABLE `tbl_guilditemboxpet` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `AccountID` int(11) DEFAULT NULL,
  `guildID` int(11) DEFAULT NULL,
  `RoomID` int(11) DEFAULT NULL,
  `BoxPosition` int(11) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guilditemboxpet
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guilditemboxpet_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guilditemboxpet_bak`;
CREATE TABLE `tbl_guilditemboxpet_bak` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `AccountID` int(11) DEFAULT NULL,
  `guildID` int(11) DEFAULT NULL,
  `RoomID` int(11) DEFAULT NULL,
  `BoxPosition` int(11) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guilditemboxpet_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guilditembox_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guilditembox_bak`;
CREATE TABLE `tbl_guilditembox_bak` (
  `ID` int(30) NOT NULL DEFAULT '0',
  `AccountID` char(30) DEFAULT NULL,
  `GuildID` char(30) DEFAULT NULL,
  `CdKey` char(30) DEFAULT NULL,
  `RegistNumber` char(30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guilditembox_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guildmember`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guildmember`;
CREATE TABLE `tbl_guildmember` (
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(10) NOT NULL DEFAULT '-1',
  `guildID` int(10) NOT NULL DEFAULT '-1',
  `titleNo` int(10) NOT NULL DEFAULT '0',
  `joinTime` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CdKey`,`RegistNumber`,`guildID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guildmember
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guildmember_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guildmember_bak`;
CREATE TABLE `tbl_guildmember_bak` (
  `CdKey` char(32) NOT NULL DEFAULT '',
  `RegistNumber` int(10) NOT NULL DEFAULT '-1',
  `guildID` int(10) NOT NULL DEFAULT '-1',
  `titleNo` int(10) NOT NULL DEFAULT '0',
  `joinTime` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`CdKey`,`RegistNumber`,`guildID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guildmember_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guildmonster`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guildmonster`;
CREATE TABLE `tbl_guildmonster` (
  `guildID` int(10) NOT NULL DEFAULT '0',
  `roomNumber` int(10) NOT NULL DEFAULT '0',
  `CdKey` char(30) NOT NULL DEFAULT '',
  `RegistNumber` int(10) NOT NULL DEFAULT '0',
  `CreateTime` int(11) NOT NULL DEFAULT '0',
  `isUse` int(11) NOT NULL DEFAULT '0',
  `AccountID` char(30) NOT NULL DEFAULT '',
  `8` int(10) NOT NULL DEFAULT '0',
  `9` int(15) NOT NULL DEFAULT '0',
  `10` int(15) NOT NULL DEFAULT '0',
  `11` int(15) NOT NULL DEFAULT '0',
  `12` int(15) NOT NULL DEFAULT '0',
  `13` int(15) NOT NULL DEFAULT '0',
  `14` int(15) NOT NULL DEFAULT '0',
  `15` int(15) NOT NULL DEFAULT '0',
  `16` int(15) NOT NULL DEFAULT '0',
  `17` int(15) NOT NULL DEFAULT '0',
  `18` int(15) NOT NULL DEFAULT '0',
  `19` int(15) NOT NULL DEFAULT '0',
  `20` int(15) NOT NULL DEFAULT '0',
  `21` int(15) NOT NULL DEFAULT '0',
  `22` int(15) NOT NULL DEFAULT '0',
  `23` int(15) NOT NULL DEFAULT '0',
  `24` int(15) NOT NULL DEFAULT '0',
  `25` int(15) NOT NULL DEFAULT '0',
  `26` int(15) NOT NULL DEFAULT '0',
  `27` int(15) NOT NULL DEFAULT '0',
  `28` int(15) NOT NULL DEFAULT '0',
  `29` int(15) NOT NULL DEFAULT '0',
  `30` int(15) NOT NULL DEFAULT '0',
  `31` int(15) NOT NULL DEFAULT '0',
  `32` int(15) NOT NULL DEFAULT '0',
  `33` int(15) NOT NULL DEFAULT '0',
  `34` int(15) NOT NULL DEFAULT '0',
  `35` int(15) NOT NULL DEFAULT '0',
  `36` int(15) NOT NULL DEFAULT '0',
  `37` int(15) NOT NULL DEFAULT '0',
  `38` int(15) NOT NULL DEFAULT '0',
  `39` int(15) NOT NULL DEFAULT '0',
  `40` int(15) NOT NULL DEFAULT '0',
  `41` int(15) NOT NULL DEFAULT '0',
  `42` int(15) NOT NULL DEFAULT '0',
  `43` int(15) NOT NULL DEFAULT '0',
  `44` int(15) NOT NULL DEFAULT '0',
  `45` int(15) NOT NULL DEFAULT '0',
  `46` int(15) NOT NULL DEFAULT '0',
  `47` int(15) NOT NULL DEFAULT '0',
  `48` int(15) NOT NULL DEFAULT '0',
  `49` int(15) NOT NULL DEFAULT '0',
  `50` int(15) NOT NULL DEFAULT '0',
  `51` int(15) NOT NULL DEFAULT '0',
  `52` int(15) NOT NULL DEFAULT '0',
  `53` int(15) NOT NULL DEFAULT '0',
  `54` int(15) NOT NULL DEFAULT '0',
  `55` int(15) NOT NULL DEFAULT '0',
  `56` int(15) NOT NULL DEFAULT '0',
  `57` int(15) NOT NULL DEFAULT '0',
  `58` int(15) NOT NULL DEFAULT '0',
  `59` int(15) NOT NULL DEFAULT '0',
  `60` int(15) NOT NULL DEFAULT '0',
  `61` int(15) NOT NULL DEFAULT '0',
  `62` int(15) NOT NULL DEFAULT '0',
  `63` int(15) NOT NULL DEFAULT '0',
  `64` int(15) NOT NULL DEFAULT '0',
  `65` int(15) NOT NULL DEFAULT '0',
  `66` int(15) NOT NULL DEFAULT '0',
  `67` int(15) NOT NULL DEFAULT '0',
  `68` int(15) NOT NULL DEFAULT '0',
  `69` int(15) NOT NULL DEFAULT '0',
  `70` int(15) NOT NULL DEFAULT '0',
  `71` int(15) NOT NULL DEFAULT '0',
  `72` int(15) NOT NULL DEFAULT '0',
  `73` int(15) NOT NULL DEFAULT '0',
  `74` int(15) NOT NULL DEFAULT '0',
  `75` int(15) NOT NULL DEFAULT '0',
  `76` int(15) NOT NULL DEFAULT '0',
  `77` int(15) NOT NULL DEFAULT '0',
  `78` int(15) NOT NULL DEFAULT '0',
  `79` int(15) NOT NULL DEFAULT '0',
  `80` int(15) NOT NULL DEFAULT '0',
  `81` int(15) NOT NULL DEFAULT '0',
  `82` int(15) NOT NULL DEFAULT '0',
  `83` int(15) NOT NULL DEFAULT '0',
  PRIMARY KEY (`guildID`,`roomNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guildmonster
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guildmonster_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guildmonster_bak`;
CREATE TABLE `tbl_guildmonster_bak` (
  `guildID` int(10) NOT NULL DEFAULT '0',
  `roomNumber` int(10) NOT NULL DEFAULT '0',
  `CdKey` char(30) NOT NULL DEFAULT '',
  `RegistNumber` int(10) NOT NULL DEFAULT '0',
  `CreateTime` int(11) NOT NULL DEFAULT '0',
  `isUse` int(11) NOT NULL DEFAULT '0',
  `AccountID` char(30) NOT NULL DEFAULT '',
  `8` int(10) NOT NULL DEFAULT '0',
  `9` int(15) NOT NULL DEFAULT '0',
  `10` int(15) NOT NULL DEFAULT '0',
  `11` int(15) NOT NULL DEFAULT '0',
  `12` int(15) NOT NULL DEFAULT '0',
  `13` int(15) NOT NULL DEFAULT '0',
  `14` int(15) NOT NULL DEFAULT '0',
  `15` int(15) NOT NULL DEFAULT '0',
  `16` int(15) NOT NULL DEFAULT '0',
  `17` int(15) NOT NULL DEFAULT '0',
  `18` int(15) NOT NULL DEFAULT '0',
  `19` int(15) NOT NULL DEFAULT '0',
  `20` int(15) NOT NULL DEFAULT '0',
  `21` int(15) NOT NULL DEFAULT '0',
  `22` int(15) NOT NULL DEFAULT '0',
  `23` int(15) NOT NULL DEFAULT '0',
  `24` int(15) NOT NULL DEFAULT '0',
  `25` int(15) NOT NULL DEFAULT '0',
  `26` int(15) NOT NULL DEFAULT '0',
  `27` int(15) NOT NULL DEFAULT '0',
  `28` int(15) NOT NULL DEFAULT '0',
  `29` int(15) NOT NULL DEFAULT '0',
  `30` int(15) NOT NULL DEFAULT '0',
  `31` int(15) NOT NULL DEFAULT '0',
  `32` int(15) NOT NULL DEFAULT '0',
  `33` int(15) NOT NULL DEFAULT '0',
  `34` int(15) NOT NULL DEFAULT '0',
  `35` int(15) NOT NULL DEFAULT '0',
  `36` int(15) NOT NULL DEFAULT '0',
  `37` int(15) NOT NULL DEFAULT '0',
  `38` int(15) NOT NULL DEFAULT '0',
  `39` int(15) NOT NULL DEFAULT '0',
  `40` int(15) NOT NULL DEFAULT '0',
  `41` int(15) NOT NULL DEFAULT '0',
  `42` int(15) NOT NULL DEFAULT '0',
  `43` int(15) NOT NULL DEFAULT '0',
  `44` int(15) NOT NULL DEFAULT '0',
  `45` int(15) NOT NULL DEFAULT '0',
  `46` int(15) NOT NULL DEFAULT '0',
  `47` int(15) NOT NULL DEFAULT '0',
  `48` int(15) NOT NULL DEFAULT '0',
  `49` int(15) NOT NULL DEFAULT '0',
  `50` int(15) NOT NULL DEFAULT '0',
  `51` int(15) NOT NULL DEFAULT '0',
  `52` int(15) NOT NULL DEFAULT '0',
  `53` int(15) NOT NULL DEFAULT '0',
  `54` int(15) NOT NULL DEFAULT '0',
  `55` int(15) NOT NULL DEFAULT '0',
  `56` int(15) NOT NULL DEFAULT '0',
  `57` int(15) NOT NULL DEFAULT '0',
  `58` int(15) NOT NULL DEFAULT '0',
  `59` int(15) NOT NULL DEFAULT '0',
  `60` int(15) NOT NULL DEFAULT '0',
  `61` int(15) NOT NULL DEFAULT '0',
  `62` int(15) NOT NULL DEFAULT '0',
  `63` int(15) NOT NULL DEFAULT '0',
  `64` int(15) NOT NULL DEFAULT '0',
  `65` int(15) NOT NULL DEFAULT '0',
  `66` int(15) NOT NULL DEFAULT '0',
  `67` int(15) NOT NULL DEFAULT '0',
  `68` int(15) NOT NULL DEFAULT '0',
  `69` int(15) NOT NULL DEFAULT '0',
  `70` int(15) NOT NULL DEFAULT '0',
  `71` int(15) NOT NULL DEFAULT '0',
  `72` int(15) NOT NULL DEFAULT '0',
  `73` int(15) NOT NULL DEFAULT '0',
  `74` int(15) NOT NULL DEFAULT '0',
  `75` int(15) NOT NULL DEFAULT '0',
  `76` int(15) NOT NULL DEFAULT '0',
  `77` int(15) NOT NULL DEFAULT '0',
  `78` int(15) NOT NULL DEFAULT '0',
  `79` int(15) NOT NULL DEFAULT '0',
  `80` int(15) NOT NULL DEFAULT '0',
  `81` int(15) NOT NULL DEFAULT '0',
  `82` int(15) NOT NULL DEFAULT '0',
  `83` int(15) NOT NULL DEFAULT '0',
  PRIMARY KEY (`guildID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guildmonster_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_guild_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_guild_bak`;
CREATE TABLE `tbl_guild_bak` (
  `Count` char(30) DEFAULT NULL,
  `guildID` char(30) DEFAULT NULL,
  `guildName` char(30) DEFAULT NULL,
  `guildMark` char(30) DEFAULT NULL,
  `CdKey` char(30) DEFAULT NULL,
  `roomType` char(30) DEFAULT NULL,
  `brief` char(30) DEFAULT NULL,
  `roomName` char(30) DEFAULT NULL,
  `createTime` char(30) DEFAULT NULL,
  `lastAccess` char(30) DEFAULT NULL,
  `titleName0` char(30) DEFAULT NULL,
  `commition0` char(30) DEFAULT NULL,
  `floorID` char(30) DEFAULT NULL,
  `serverNumber` char(30) DEFAULT NULL,
  `SkillNum` char(30) DEFAULT NULL,
  `SkillID` char(30) DEFAULT NULL,
  `SkillLevel` char(30) DEFAULT NULL,
  `SkillExp` char(30) DEFAULT NULL,
  `SeqNo` char(30) DEFAULT NULL,
  `RegistNumber` char(30) DEFAULT NULL,
  `Name` char(30) DEFAULT NULL,
  `Action` char(30) DEFAULT NULL,
  `MonsterNo` char(30) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_guild_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_item`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_item`;
CREATE TABLE `tbl_item` (
  `ITEM_ID` int(11) DEFAULT '0',
  `ITEM_BASEIMAGENUMBER` int(11) DEFAULT NULL,
  `ITEM_COST` int(11) DEFAULT NULL,
  `ITEM_TYPE` int(11) DEFAULT NULL,
  `ITEM_OTHERFLG` int(11) DEFAULT NULL,
  `ITEM_EQUIPBOTHHAND` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEFIELD` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEBATTLE` int(11) DEFAULT NULL,
  `ITEM_TARGET` int(11) DEFAULT NULL,
  `ITEM_REMAIN` int(11) DEFAULT NULL,
  `ITEM_MAXREMAIN` int(11) DEFAULT NULL,
  `ITEM_LEVEL` int(11) DEFAULT NULL,
  `ITEM_BASEFAILEDPROB` int(11) DEFAULT NULL,
  `ITEM_MAXDURABILITY` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MIN` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MAX` int(11) DEFAULT NULL,
  `ITEM_ABLEEFFECTBETWEENHAVE` int(11) DEFAULT NULL,
  `ITEM_MODIFYMODFLG` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTACK` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEFENCE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAGILITY` int(11) DEFAULT NULL,
  `ITEM_MODIFYMAGIC` int(11) DEFAULT NULL,
  `ITEM_MODIFYRECOVERY` int(11) DEFAULT NULL,
  `ITEM_MODIFYCRITICAL` int(11) DEFAULT NULL,
  `ITEM_MODIFYCOUNTER` int(11) DEFAULT NULL,
  `ITEM_MODIFYHITRATE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAVOID` int(11) DEFAULT NULL,
  `ITEM_MODIFYHP` int(11) DEFAULT NULL,
  `ITEM_MODIFYFORCEPOINT` int(11) DEFAULT NULL,
  `ITEM_MODIFYLUCK` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARISMA` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARM` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB2` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE2` int(11) DEFAULT NULL,
  `ITEM_MODIFYSTAMINA` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEX` int(11) DEFAULT NULL,
  `ITEM_MODIFYINTELLIGENCE` int(11) DEFAULT NULL,
  `ITEM_POISON` int(11) DEFAULT NULL,
  `ITEM_SLEEP` int(11) DEFAULT NULL,
  `ITEM_STONE` int(11) DEFAULT NULL,
  `ITEM_DRUNK` int(11) DEFAULT NULL,
  `ITEM_CONFUSION` int(11) DEFAULT NULL,
  `ITEM_AMNESIA` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECT` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE2` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_WEAPON` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ARMOUR` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ACCESSORY` int(11) DEFAULT NULL,
  `ITEM_USEACTION` int(11) DEFAULT NULL,
  `ITEM_DROPATLOGOUT` int(11) DEFAULT NULL,
  `ITEM_VANISHATDROP` int(11) DEFAULT NULL,
  `ITEM_CANPETMAIL` int(11) DEFAULT NULL,
  `ITEM_RSS` int(11) DEFAULT NULL,
  `ITEM_CANSELL` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION1` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION2` int(11) DEFAULT NULL,
  `ITEM_LEAKEDPROB` int(11) DEFAULT NULL,
  `ITEM_RARE_FLG` int(11) DEFAULT NULL,
  `ITEM_INBOX_FLG` int(11) DEFAULT NULL,
  `ITEM_PUTTIME` int(11) DEFAULT NULL,
  `ITEM_LEAKLEVEL` int(11) DEFAULT NULL,
  `ITEM_MERGEFLG` int(11) DEFAULT NULL,
  `ITEM_DURABILITY` int(11) DEFAULT NULL,
  `ITEM_SELLUNIT` int(11) DEFAULT NULL,
  `ITEM_CREATETIME` int(11) DEFAULT NULL,
  `ITEM_VAR1` int(11) DEFAULT NULL,
  `ITEM_VAR2` int(11) DEFAULT NULL,
  `ITEM_VAR3` int(11) DEFAULT NULL,
  `ITEM_VAR4` int(11) DEFAULT NULL,
  `ITEM_ADM` int(11) DEFAULT NULL,
  `ITEM_HOUSE_X` int(11) DEFAULT NULL,
  `ITEM_HOUSE_Y` int(11) DEFAULT NULL,
  `ITEM_FIRSTNAME` char(32) DEFAULT NULL,
  `ITEM_TRUENAME` char(32) DEFAULT NULL,
  `ITEM_MEMO` char(32) DEFAULT NULL,
  `ITEM_ARGUMENT` char(32) DEFAULT NULL,
  `ITEM_RENAMECDKEY` char(32) DEFAULT NULL,
  `ITEM_FIRSTFUNCTION` char(32) DEFAULT NULL,
  `ITEM_WATCHFUNC` char(32) DEFAULT NULL,
  `ITEM_USEFUNC` char(32) DEFAULT NULL,
  `ITEM_ATTACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DETACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DROPFUNC` char(32) DEFAULT NULL,
  `ITEM_PREPICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_PICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_LASTFUNCTION` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `ITEMDATAPLACENUMBER` int(11) unsigned DEFAULT NULL,
  `ITEM_SAVENUM` int(11) DEFAULT NULL,
  KEY `tbl_item` (`CdKey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_item
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_item_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_item_bak`;
CREATE TABLE `tbl_item_bak` (
  `ITEM_ID` int(11) DEFAULT '0',
  `ITEM_BASEIMAGENUMBER` int(11) DEFAULT NULL,
  `ITEM_COST` int(11) DEFAULT NULL,
  `ITEM_TYPE` int(11) DEFAULT NULL,
  `ITEM_OTHERFLG` int(11) DEFAULT NULL,
  `ITEM_EQUIPBOTHHAND` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEFIELD` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEBATTLE` int(11) DEFAULT NULL,
  `ITEM_TARGET` int(11) DEFAULT NULL,
  `ITEM_REMAIN` int(11) DEFAULT NULL,
  `ITEM_MAXREMAIN` int(11) DEFAULT NULL,
  `ITEM_LEVEL` int(11) DEFAULT NULL,
  `ITEM_BASEFAILEDPROB` int(11) DEFAULT NULL,
  `ITEM_MAXDURABILITY` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MIN` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MAX` int(11) DEFAULT NULL,
  `ITEM_ABLEEFFECTBETWEENHAVE` int(11) DEFAULT NULL,
  `ITEM_MODIFYMODFLG` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTACK` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEFENCE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAGILITY` int(11) DEFAULT NULL,
  `ITEM_MODIFYMAGIC` int(11) DEFAULT NULL,
  `ITEM_MODIFYRECOVERY` int(11) DEFAULT NULL,
  `ITEM_MODIFYCRITICAL` int(11) DEFAULT NULL,
  `ITEM_MODIFYCOUNTER` int(11) DEFAULT NULL,
  `ITEM_MODIFYHITRATE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAVOID` int(11) DEFAULT NULL,
  `ITEM_MODIFYHP` int(11) DEFAULT NULL,
  `ITEM_MODIFYFORCEPOINT` int(11) DEFAULT NULL,
  `ITEM_MODIFYLUCK` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARISMA` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARM` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB2` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE2` int(11) DEFAULT NULL,
  `ITEM_MODIFYSTAMINA` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEX` int(11) DEFAULT NULL,
  `ITEM_MODIFYINTELLIGENCE` int(11) DEFAULT NULL,
  `ITEM_POISON` int(11) DEFAULT NULL,
  `ITEM_SLEEP` int(11) DEFAULT NULL,
  `ITEM_STONE` int(11) DEFAULT NULL,
  `ITEM_DRUNK` int(11) DEFAULT NULL,
  `ITEM_CONFUSION` int(11) DEFAULT NULL,
  `ITEM_AMNESIA` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECT` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE2` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_WEAPON` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ARMOUR` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ACCESSORY` int(11) DEFAULT NULL,
  `ITEM_USEACTION` int(11) DEFAULT NULL,
  `ITEM_DROPATLOGOUT` int(11) DEFAULT NULL,
  `ITEM_VANISHATDROP` int(11) DEFAULT NULL,
  `ITEM_CANPETMAIL` int(11) DEFAULT NULL,
  `ITEM_RSS` int(11) DEFAULT NULL,
  `ITEM_CANSELL` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION1` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION2` int(11) DEFAULT NULL,
  `ITEM_LEAKEDPROB` int(11) DEFAULT NULL,
  `ITEM_RARE_FLG` int(11) DEFAULT NULL,
  `ITEM_INBOX_FLG` int(11) DEFAULT NULL,
  `ITEM_PUTTIME` int(11) DEFAULT NULL,
  `ITEM_LEAKLEVEL` int(11) DEFAULT NULL,
  `ITEM_MERGEFLG` int(11) DEFAULT NULL,
  `ITEM_DURABILITY` int(11) DEFAULT NULL,
  `ITEM_SELLUNIT` int(11) DEFAULT NULL,
  `ITEM_CREATETIME` int(11) DEFAULT NULL,
  `ITEM_VAR1` int(11) DEFAULT NULL,
  `ITEM_VAR2` int(11) DEFAULT NULL,
  `ITEM_VAR3` int(11) DEFAULT NULL,
  `ITEM_VAR4` int(11) DEFAULT NULL,
  `ITEM_ADM` int(11) DEFAULT NULL,
  `ITEM_HOUSE_X` int(11) DEFAULT NULL,
  `ITEM_HOUSE_Y` int(11) DEFAULT NULL,
  `ITEM_FIRSTNAME` char(32) DEFAULT NULL,
  `ITEM_TRUENAME` char(32) DEFAULT NULL,
  `ITEM_MEMO` char(32) DEFAULT NULL,
  `ITEM_ARGUMENT` char(32) DEFAULT NULL,
  `ITEM_RENAMECDKEY` char(32) DEFAULT NULL,
  `ITEM_FIRSTFUNCTION` char(32) DEFAULT NULL,
  `ITEM_WATCHFUNC` char(32) DEFAULT NULL,
  `ITEM_USEFUNC` char(32) DEFAULT NULL,
  `ITEM_ATTACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DETACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DROPFUNC` char(32) DEFAULT NULL,
  `ITEM_PREPICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_PICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_LASTFUNCTION` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `ITEMDATAPLACENUMBER` int(11) unsigned DEFAULT NULL,
  `ITEM_SAVENUM` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_item_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_item_down`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_item_down`;
CREATE TABLE `tbl_item_down` (
  `ITEM_ID` int(11) DEFAULT '0',
  `ITEM_BASEIMAGENUMBER` int(11) DEFAULT NULL,
  `ITEM_COST` int(11) DEFAULT NULL,
  `ITEM_TYPE` int(11) DEFAULT NULL,
  `ITEM_OTHERFLG` int(11) DEFAULT NULL,
  `ITEM_EQUIPBOTHHAND` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEFIELD` int(11) DEFAULT NULL,
  `ITEM_ABLEUSEBATTLE` int(11) DEFAULT NULL,
  `ITEM_TARGET` int(11) DEFAULT NULL,
  `ITEM_REMAIN` int(11) DEFAULT NULL,
  `ITEM_MAXREMAIN` int(11) DEFAULT NULL,
  `ITEM_LEVEL` int(11) DEFAULT NULL,
  `ITEM_BASEFAILEDPROB` int(11) DEFAULT NULL,
  `ITEM_MAXDURABILITY` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MIN` int(11) DEFAULT NULL,
  `ITEM_ATTACKNUM_MAX` int(11) DEFAULT NULL,
  `ITEM_ABLEEFFECTBETWEENHAVE` int(11) DEFAULT NULL,
  `ITEM_MODIFYMODFLG` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTACK` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEFENCE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAGILITY` int(11) DEFAULT NULL,
  `ITEM_MODIFYMAGIC` int(11) DEFAULT NULL,
  `ITEM_MODIFYRECOVERY` int(11) DEFAULT NULL,
  `ITEM_MODIFYCRITICAL` int(11) DEFAULT NULL,
  `ITEM_MODIFYCOUNTER` int(11) DEFAULT NULL,
  `ITEM_MODIFYHITRATE` int(11) DEFAULT NULL,
  `ITEM_MODIFYAVOID` int(11) DEFAULT NULL,
  `ITEM_MODIFYHP` int(11) DEFAULT NULL,
  `ITEM_MODIFYFORCEPOINT` int(11) DEFAULT NULL,
  `ITEM_MODIFYLUCK` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARISMA` int(11) DEFAULT NULL,
  `ITEM_MODIFYCHARM` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIB2` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE` int(11) DEFAULT NULL,
  `ITEM_MODIFYATTRIBVALUE2` int(11) DEFAULT NULL,
  `ITEM_MODIFYSTAMINA` int(11) DEFAULT NULL,
  `ITEM_MODIFYDEX` int(11) DEFAULT NULL,
  `ITEM_MODIFYINTELLIGENCE` int(11) DEFAULT NULL,
  `ITEM_POISON` int(11) DEFAULT NULL,
  `ITEM_SLEEP` int(11) DEFAULT NULL,
  `ITEM_STONE` int(11) DEFAULT NULL,
  `ITEM_DRUNK` int(11) DEFAULT NULL,
  `ITEM_CONFUSION` int(11) DEFAULT NULL,
  `ITEM_AMNESIA` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECT` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE` int(11) DEFAULT NULL,
  `ITEM_SPECIALEFFECTVALUE2` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_WEAPON` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ARMOUR` int(11) DEFAULT NULL,
  `ITEM_MATERIAL_ACCESSORY` int(11) DEFAULT NULL,
  `ITEM_USEACTION` int(11) DEFAULT NULL,
  `ITEM_DROPATLOGOUT` int(11) DEFAULT NULL,
  `ITEM_VANISHATDROP` int(11) DEFAULT NULL,
  `ITEM_CANPETMAIL` int(11) DEFAULT NULL,
  `ITEM_RSS` int(11) DEFAULT NULL,
  `ITEM_CANSELL` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION1` int(11) DEFAULT NULL,
  `ITEM_EXPLANATION2` int(11) DEFAULT NULL,
  `ITEM_LEAKEDPROB` int(11) DEFAULT NULL,
  `ITEM_RARE_FLG` int(11) DEFAULT NULL,
  `ITEM_INBOX_FLG` int(11) DEFAULT NULL,
  `ITEM_PUTTIME` int(11) DEFAULT NULL,
  `ITEM_LEAKLEVEL` int(11) DEFAULT NULL,
  `ITEM_MERGEFLG` int(11) DEFAULT NULL,
  `ITEM_DURABILITY` int(11) DEFAULT NULL,
  `ITEM_SELLUNIT` int(11) DEFAULT NULL,
  `ITEM_CREATETIME` int(11) DEFAULT NULL,
  `ITEM_VAR1` int(11) DEFAULT NULL,
  `ITEM_VAR2` int(11) DEFAULT NULL,
  `ITEM_VAR3` int(11) DEFAULT NULL,
  `ITEM_VAR4` int(11) DEFAULT NULL,
  `ITEM_ADM` int(11) DEFAULT NULL,
  `ITEM_HOUSE_X` int(11) DEFAULT NULL,
  `ITEM_HOUSE_Y` int(11) DEFAULT NULL,
  `ITEM_FIRSTNAME` char(32) DEFAULT NULL,
  `ITEM_TRUENAME` char(32) DEFAULT NULL,
  `ITEM_MEMO` char(32) DEFAULT NULL,
  `ITEM_ARGUMENT` char(32) DEFAULT NULL,
  `ITEM_RENAMECDKEY` char(32) DEFAULT NULL,
  `ITEM_FIRSTFUNCTION` char(32) DEFAULT NULL,
  `ITEM_WATCHFUNC` char(32) DEFAULT NULL,
  `ITEM_USEFUNC` char(32) DEFAULT NULL,
  `ITEM_ATTACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DETACHFUNC` char(32) DEFAULT NULL,
  `ITEM_DROPFUNC` char(32) DEFAULT NULL,
  `ITEM_PREPICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_PICKUPFUNC` char(32) DEFAULT NULL,
  `ITEM_LASTFUNCTION` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `ITEMDATAPLACENUMBER` int(11) unsigned DEFAULT NULL,
  `ITEM_SAVENUM` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_item_down
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_lock`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_lock`;
CREATE TABLE `tbl_lock` (
  `ID` int(11) DEFAULT '1',
  `ServerName` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `LoginTime` int(11) DEFAULT NULL,
  `CdKey` char(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`CdKey`),
  KEY `index` (`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_lock
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_pet`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_pet`;
CREATE TABLE `tbl_pet` (
  `unk1` int(11) NOT NULL DEFAULT '0',
  `BaseImgnum` int(11) DEFAULT NULL,
  `Basebaseimgnum` int(11) DEFAULT NULL,
  `unk4` int(11) DEFAULT NULL,
  `unk5` int(11) DEFAULT NULL,
  `unk6` int(11) DEFAULT NULL,
  `unk7` int(11) DEFAULT NULL,
  `unk8` int(11) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `HP` int(11) DEFAULT NULL,
  `MP` int(11) DEFAULT NULL,
  `Vital` int(11) DEFAULT NULL,
  `Str` int(11) DEFAULT NULL,
  `Tgh` int(11) DEFAULT NULL,
  `Quick` int(11) DEFAULT NULL,
  `Migic` int(11) DEFAULT NULL,
  `unk17` int(11) DEFAULT NULL,
  `Race` int(11) DEFAULT NULL,
  `Attrib_Fire` int(11) DEFAULT NULL,
  `Attrib_Wind` int(11) DEFAULT NULL,
  `Attrib_Earth` int(11) DEFAULT NULL,
  `Attrib_Water` int(11) DEFAULT NULL,
  `unk23` int(11) DEFAULT NULL,
  `unk24` int(11) DEFAULT NULL,
  `unk25` int(11) DEFAULT NULL,
  `unk26` int(11) DEFAULT NULL,
  `unk27` int(11) DEFAULT NULL,
  `unk28` int(11) DEFAULT NULL,
  `unk29` int(11) DEFAULT NULL,
  `unk30` int(11) DEFAULT NULL,
  `unk31` int(11) DEFAULT NULL,
  `unk32` int(11) DEFAULT NULL,
  `unk33` int(11) DEFAULT NULL,
  `unk34` int(11) DEFAULT NULL,
  `unk35` int(11) DEFAULT NULL,
  `unk36` int(11) DEFAULT NULL,
  `unk37` int(11) DEFAULT NULL,
  `unk38` int(11) DEFAULT NULL,
  `unk39` int(11) DEFAULT NULL,
  `unk40` int(11) DEFAULT NULL,
  `unk41` int(11) DEFAULT NULL,
  `EXP` int(11) DEFAULT NULL,
  `BounsPoint` int(11) DEFAULT NULL,
  `unk44` int(11) DEFAULT NULL,
  `unk45` int(11) DEFAULT NULL,
  `PutPetTime` int(11) DEFAULT NULL,
  `unk47` int(11) DEFAULT NULL,
  `unk48` int(11) DEFAULT NULL,
  `unk49` int(11) DEFAULT NULL,
  `unk50` int(11) DEFAULT NULL,
  `unk51` int(11) DEFAULT NULL,
  `unk52` int(11) DEFAULT NULL,
  `unk53` int(11) DEFAULT NULL,
  `unk54` int(11) DEFAULT NULL,
  `unk55` int(11) DEFAULT NULL,
  `unk56` int(11) DEFAULT NULL,
  `unk57` int(11) DEFAULT NULL,
  `unk58` int(11) DEFAULT NULL,
  `unk59` int(11) DEFAULT NULL,
  `unk60` int(11) DEFAULT NULL,
  `unk61` int(11) DEFAULT NULL,
  `unk62` int(11) DEFAULT NULL,
  `unk63` int(11) DEFAULT NULL,
  `unk64` int(11) DEFAULT NULL,
  `unk65` int(11) DEFAULT NULL,
  `unk66` int(11) DEFAULT NULL,
  `unk67` int(11) DEFAULT NULL,
  `unk68` int(11) DEFAULT NULL,
  `unk69` int(11) DEFAULT NULL,
  `unk70` int(11) DEFAULT NULL,
  `unk71` int(11) DEFAULT NULL,
  `unk72` int(11) DEFAULT NULL,
  `unk73` int(11) DEFAULT NULL,
  `unk74` int(11) DEFAULT NULL,
  `unk75` int(11) DEFAULT NULL,
  `unk76` int(11) DEFAULT NULL,
  `unk77` int(11) DEFAULT NULL,
  `unk78` int(11) DEFAULT NULL,
  `unk79` int(11) DEFAULT NULL,
  `unk80` int(11) DEFAULT NULL,
  `unk81` int(11) DEFAULT NULL,
  `unk82` int(11) DEFAULT NULL,
  `unk83` int(11) DEFAULT NULL,
  `unk84` int(11) DEFAULT NULL,
  `unk85` int(11) DEFAULT NULL,
  `unk86` int(11) DEFAULT NULL,
  `unk87` int(11) DEFAULT NULL,
  `unk88` int(11) DEFAULT NULL,
  `unk89` int(11) DEFAULT NULL,
  `unk90` int(11) DEFAULT NULL,
  `unk91` int(11) DEFAULT NULL,
  `unk92` int(11) DEFAULT NULL,
  `PetName` char(32) DEFAULT NULL,
  `UserPetName` char(32) DEFAULT NULL,
  `unk95` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `OwnerName` char(32) DEFAULT NULL,
  `unk98` int(11) DEFAULT NULL,
  `OwnerCdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `Position` int(11) DEFAULT NULL,
  `unk102` int(11) DEFAULT NULL,
  KEY `index` (`RegistNumber`,`CdKey`,`OwnerCdKey`),
  KEY `index2` (`RegistNumber`,`CdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_pet
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_pet_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_pet_bak`;
CREATE TABLE `tbl_pet_bak` (
  `unk1` int(11) NOT NULL DEFAULT '0',
  `BaseImgnum` int(11) DEFAULT NULL,
  `Basebaseimgnum` int(11) DEFAULT NULL,
  `unk4` int(11) DEFAULT NULL,
  `unk5` int(11) DEFAULT NULL,
  `unk6` int(11) DEFAULT NULL,
  `unk7` int(11) DEFAULT NULL,
  `unk8` int(11) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `HP` int(11) DEFAULT NULL,
  `MP` int(11) DEFAULT NULL,
  `Vital` int(11) DEFAULT NULL,
  `Str` int(11) DEFAULT NULL,
  `Tgh` int(11) DEFAULT NULL,
  `Quick` int(11) DEFAULT NULL,
  `Migic` int(11) DEFAULT NULL,
  `unk17` int(11) DEFAULT NULL,
  `Race` int(11) DEFAULT NULL,
  `Attrib_Fire` int(11) DEFAULT NULL,
  `Attrib_Wind` int(11) DEFAULT NULL,
  `Attrib_Earth` int(11) DEFAULT NULL,
  `Attrib_Water` int(11) DEFAULT NULL,
  `unk23` int(11) DEFAULT NULL,
  `unk24` int(11) DEFAULT NULL,
  `unk25` int(11) DEFAULT NULL,
  `unk26` int(11) DEFAULT NULL,
  `unk27` int(11) DEFAULT NULL,
  `unk28` int(11) DEFAULT NULL,
  `unk29` int(11) DEFAULT NULL,
  `unk30` int(11) DEFAULT NULL,
  `unk31` int(11) DEFAULT NULL,
  `unk32` int(11) DEFAULT NULL,
  `unk33` int(11) DEFAULT NULL,
  `unk34` int(11) DEFAULT NULL,
  `unk35` int(11) DEFAULT NULL,
  `unk36` int(11) DEFAULT NULL,
  `unk37` int(11) DEFAULT NULL,
  `unk38` int(11) DEFAULT NULL,
  `unk39` int(11) DEFAULT NULL,
  `unk40` int(11) DEFAULT NULL,
  `unk41` int(11) DEFAULT NULL,
  `EXP` int(11) DEFAULT NULL,
  `BounsPoint` int(11) DEFAULT NULL,
  `unk44` int(11) DEFAULT NULL,
  `unk45` int(11) DEFAULT NULL,
  `PutPetTime` int(11) DEFAULT NULL,
  `unk47` int(11) DEFAULT NULL,
  `unk48` int(11) DEFAULT NULL,
  `unk49` int(11) DEFAULT NULL,
  `unk50` int(11) DEFAULT NULL,
  `unk51` int(11) DEFAULT NULL,
  `unk52` int(11) DEFAULT NULL,
  `unk53` int(11) DEFAULT NULL,
  `unk54` int(11) DEFAULT NULL,
  `unk55` int(11) DEFAULT NULL,
  `unk56` int(11) DEFAULT NULL,
  `unk57` int(11) DEFAULT NULL,
  `unk58` int(11) DEFAULT NULL,
  `unk59` int(11) DEFAULT NULL,
  `unk60` int(11) DEFAULT NULL,
  `unk61` int(11) DEFAULT NULL,
  `unk62` int(11) DEFAULT NULL,
  `unk63` int(11) DEFAULT NULL,
  `unk64` int(11) DEFAULT NULL,
  `unk65` int(11) DEFAULT NULL,
  `unk66` int(11) DEFAULT NULL,
  `unk67` int(11) DEFAULT NULL,
  `unk68` int(11) DEFAULT NULL,
  `unk69` int(11) DEFAULT NULL,
  `unk70` int(11) DEFAULT NULL,
  `unk71` int(11) DEFAULT NULL,
  `unk72` int(11) DEFAULT NULL,
  `unk73` int(11) DEFAULT NULL,
  `unk74` int(11) DEFAULT NULL,
  `unk75` int(11) DEFAULT NULL,
  `unk76` int(11) DEFAULT NULL,
  `unk77` int(11) DEFAULT NULL,
  `unk78` int(11) DEFAULT NULL,
  `unk79` int(11) DEFAULT NULL,
  `unk80` int(11) DEFAULT NULL,
  `unk81` int(11) DEFAULT NULL,
  `unk82` int(11) DEFAULT NULL,
  `unk83` int(11) DEFAULT NULL,
  `unk84` int(11) DEFAULT NULL,
  `unk85` int(11) DEFAULT NULL,
  `unk86` int(11) DEFAULT NULL,
  `unk87` int(11) DEFAULT NULL,
  `unk88` int(11) DEFAULT NULL,
  `unk89` int(11) DEFAULT NULL,
  `unk90` int(11) DEFAULT NULL,
  `unk91` int(11) DEFAULT NULL,
  `unk92` int(11) DEFAULT NULL,
  `PetName` char(32) DEFAULT NULL,
  `UserPetName` char(32) DEFAULT NULL,
  `unk95` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `OwnerName` char(32) DEFAULT NULL,
  `unk98` int(11) DEFAULT NULL,
  `OwnerCdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `Position` int(11) DEFAULT NULL,
  `unk102` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_pet_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_pet_down`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_pet_down`;
CREATE TABLE `tbl_pet_down` (
  `unk1` int(11) NOT NULL DEFAULT '0',
  `BaseImgnum` int(11) DEFAULT NULL,
  `Basebaseimgnum` int(11) DEFAULT NULL,
  `unk4` int(11) DEFAULT NULL,
  `unk5` int(11) DEFAULT NULL,
  `unk6` int(11) DEFAULT NULL,
  `unk7` int(11) DEFAULT NULL,
  `unk8` int(11) DEFAULT NULL,
  `LEVEL` int(11) DEFAULT NULL,
  `HP` int(11) DEFAULT NULL,
  `MP` int(11) DEFAULT NULL,
  `Vital` int(11) DEFAULT NULL,
  `Str` int(11) DEFAULT NULL,
  `Tgh` int(11) DEFAULT NULL,
  `Quick` int(11) DEFAULT NULL,
  `Migic` int(11) DEFAULT NULL,
  `unk17` int(11) DEFAULT NULL,
  `Race` int(11) DEFAULT NULL,
  `Attrib_Fire` int(11) DEFAULT NULL,
  `Attrib_Wind` int(11) DEFAULT NULL,
  `Attrib_Earth` int(11) DEFAULT NULL,
  `Attrib_Water` int(11) DEFAULT NULL,
  `unk23` int(11) DEFAULT NULL,
  `unk24` int(11) DEFAULT NULL,
  `unk25` int(11) DEFAULT NULL,
  `unk26` int(11) DEFAULT NULL,
  `unk27` int(11) DEFAULT NULL,
  `unk28` int(11) DEFAULT NULL,
  `unk29` int(11) DEFAULT NULL,
  `unk30` int(11) DEFAULT NULL,
  `unk31` int(11) DEFAULT NULL,
  `unk32` int(11) DEFAULT NULL,
  `unk33` int(11) DEFAULT NULL,
  `unk34` int(11) DEFAULT NULL,
  `unk35` int(11) DEFAULT NULL,
  `unk36` int(11) DEFAULT NULL,
  `unk37` int(11) DEFAULT NULL,
  `unk38` int(11) DEFAULT NULL,
  `unk39` int(11) DEFAULT NULL,
  `unk40` int(11) DEFAULT NULL,
  `unk41` int(11) DEFAULT NULL,
  `EXP` int(11) DEFAULT NULL,
  `BounsPoint` int(11) DEFAULT NULL,
  `unk44` int(11) DEFAULT NULL,
  `unk45` int(11) DEFAULT NULL,
  `PutPetTime` int(11) DEFAULT NULL,
  `unk47` int(11) DEFAULT NULL,
  `unk48` int(11) DEFAULT NULL,
  `unk49` int(11) DEFAULT NULL,
  `unk50` int(11) DEFAULT NULL,
  `unk51` int(11) DEFAULT NULL,
  `unk52` int(11) DEFAULT NULL,
  `unk53` int(11) DEFAULT NULL,
  `unk54` int(11) DEFAULT NULL,
  `unk55` int(11) DEFAULT NULL,
  `unk56` int(11) DEFAULT NULL,
  `unk57` int(11) DEFAULT NULL,
  `unk58` int(11) DEFAULT NULL,
  `unk59` int(11) DEFAULT NULL,
  `unk60` int(11) DEFAULT NULL,
  `unk61` int(11) DEFAULT NULL,
  `unk62` int(11) DEFAULT NULL,
  `unk63` int(11) DEFAULT NULL,
  `unk64` int(11) DEFAULT NULL,
  `unk65` int(11) DEFAULT NULL,
  `unk66` int(11) DEFAULT NULL,
  `unk67` int(11) DEFAULT NULL,
  `unk68` int(11) DEFAULT NULL,
  `unk69` int(11) DEFAULT NULL,
  `unk70` int(11) DEFAULT NULL,
  `unk71` int(11) DEFAULT NULL,
  `unk72` int(11) DEFAULT NULL,
  `unk73` int(11) DEFAULT NULL,
  `unk74` int(11) DEFAULT NULL,
  `unk75` int(11) DEFAULT NULL,
  `unk76` int(11) DEFAULT NULL,
  `unk77` int(11) DEFAULT NULL,
  `unk78` int(11) DEFAULT NULL,
  `unk79` int(11) DEFAULT NULL,
  `unk80` int(11) DEFAULT NULL,
  `unk81` int(11) DEFAULT NULL,
  `unk82` int(11) DEFAULT NULL,
  `unk83` int(11) DEFAULT NULL,
  `unk84` int(11) DEFAULT NULL,
  `unk85` int(11) DEFAULT NULL,
  `unk86` int(11) DEFAULT NULL,
  `unk87` int(11) DEFAULT NULL,
  `unk88` int(11) DEFAULT NULL,
  `unk89` int(11) DEFAULT NULL,
  `unk90` int(11) DEFAULT NULL,
  `unk91` int(11) DEFAULT NULL,
  `unk92` int(11) DEFAULT NULL,
  `PetName` char(32) DEFAULT NULL,
  `UserPetName` char(32) DEFAULT NULL,
  `unk95` char(32) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `OwnerName` char(32) DEFAULT NULL,
  `unk98` int(11) DEFAULT NULL,
  `OwnerCdKey` char(32) DEFAULT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `Position` int(11) DEFAULT NULL,
  `unk102` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_pet_down
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_playernum`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_playernum`;
CREATE TABLE `tbl_playernum` (
  `num` char(30) NOT NULL DEFAULT '',
  `CharList` char(30) DEFAULT NULL,
  `trial-flg` char(30) DEFAULT NULL,
  `NewChar` char(30) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_playernum
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_product`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_product`;
CREATE TABLE `tbl_product` (
  `ProductKey` char(30) DEFAULT NULL,
  `Kind` char(30) DEFAULT NULL,
  `UseFlg` char(30) DEFAULT NULL,
  `LinkCdKey` char(30) DEFAULT NULL,
  `EnableFlg` char(30) DEFAULT NULL,
  `VerUpDate` char(30) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_product
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_puk2`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_puk2`;
CREATE TABLE `tbl_puk2` (
  `Puk2Key` char(30) DEFAULT NULL,
  `Kind` char(30) DEFAULT NULL,
  `UseFlg` char(30) DEFAULT NULL,
  `LinkCdKey` char(30) NOT NULL DEFAULT '',
  `EnableFlg` char(30) DEFAULT NULL,
  `VerUpDate` char(30) DEFAULT NULL,
  PRIMARY KEY (`LinkCdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_puk2
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_puk3`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_puk3`;
CREATE TABLE `tbl_puk3` (
  `Puk3Key` char(30) DEFAULT NULL,
  `Kind` char(30) DEFAULT NULL,
  `UseFlg` char(30) DEFAULT NULL,
  `LinkCdKey` char(30) NOT NULL DEFAULT '',
  `EnableFlg` char(30) DEFAULT NULL,
  `VerUpDate` char(30) DEFAULT NULL,
  PRIMARY KEY (`LinkCdKey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_puk3
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_skill`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_skill`;
CREATE TABLE `tbl_skill` (
  `Cdkey` char(32) NOT NULL,
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `SkillNum` int(11) NOT NULL DEFAULT '0',
  `SkillID` int(11) DEFAULT NULL,
  `SkillLevel` int(11) DEFAULT NULL,
  `SkillExp` int(11) DEFAULT NULL,
  `SeqNo` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Cdkey`,`RegistNumber`,`SkillNum`),
  KEY `index` (`Cdkey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312 ROW_FORMAT=FIXED;

-- ----------------------------
-- Records of tbl_skill
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_skillpopulation`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_skillpopulation`;
CREATE TABLE `tbl_skillpopulation` (
  `Cdkey` char(32) NOT NULL,
  `RegistNumber` int(11) DEFAULT NULL,
  `SkillID` int(11) DEFAULT NULL,
  `SkillNum` int(11) DEFAULT NULL,
  `SkillLevel` int(11) DEFAULT NULL,
  `SkillExp` int(11) DEFAULT NULL,
  `SeqNo` int(11) DEFAULT NULL,
  PRIMARY KEY (`Cdkey`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_skillpopulation
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_skill_bak`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_skill_bak`;
CREATE TABLE `tbl_skill_bak` (
  `Cdkey` char(32) NOT NULL,
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `SkillNum` int(11) NOT NULL DEFAULT '0',
  `SkillID` int(11) DEFAULT NULL,
  `SkillLevel` int(11) DEFAULT NULL,
  `SkillExp` int(11) DEFAULT NULL,
  `SeqNo` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Cdkey`,`RegistNumber`,`SkillNum`),
  KEY `index` (`Cdkey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312 ROW_FORMAT=FIXED;

-- ----------------------------
-- Records of tbl_skill_bak
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_skill_down`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_skill_down`;
CREATE TABLE `tbl_skill_down` (
  `Cdkey` char(32) NOT NULL,
  `RegistNumber` int(11) NOT NULL DEFAULT '0',
  `SkillNum` int(11) NOT NULL DEFAULT '0',
  `SkillID` int(11) DEFAULT NULL,
  `SkillLevel` int(11) DEFAULT NULL,
  `SkillExp` int(11) DEFAULT NULL,
  `SeqNo` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Cdkey`,`RegistNumber`,`SkillNum`),
  KEY `index` (`Cdkey`,`RegistNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312 ROW_FORMAT=FIXED;

-- ----------------------------
-- Records of tbl_skill_down
-- ----------------------------

-- ----------------------------
-- Table structure for `tbl_user`
-- ----------------------------
DROP TABLE IF EXISTS `tbl_user`;
CREATE TABLE `tbl_user` (
  `AccountID` char(32) NOT NULL DEFAULT '',
  `AccountPassword` char(32) DEFAULT NULL,
  `EnableFlg` int(11) DEFAULT NULL,
  `TrialFlg` int(11) NOT NULL DEFAULT '8',
  `DownFlg` int(11) DEFAULT NULL,
  `ExpFlg` int(11) DEFAULT NULL,
  `SequenceNumber` int(11) DEFAULT NULL,
  `UseFlg` int(11) DEFAULT NULL,
  `BadMsg` int(11) DEFAULT NULL,
  `CdKey` char(32) DEFAULT NULL,
  `IP` char(15) DEFAULT NULL,
  PRIMARY KEY (`AccountID`)
) ENGINE=MyISAM DEFAULT CHARSET=gb2312;

-- ----------------------------
-- Records of tbl_user
-- ----------------------------
